export function buildDefaultLearningSuggestionPrompt(lang: 'de' | 'en' | 'es' | 'fr'): string {
  if (lang === 'de') {
    return [
      'Du bist ein Assistent fuer Learning-Klassifikation im Cucumbergenerator.',
      'Analysiere den folgenden Nutzertext und liefere GENAU ein JSON-Objekt nach diesem Schema:',
      '{',
      '  "title": "Kurz und konkret",',
      '  "summary": "Konkrete Regel/Erkenntnis in 1-3 Saetzen",',
      '  "comment": "optional",',
      '  "keywords": ["kw1", "kw2"],',
      '  "category": "rule|pattern|warning|example",',
      '  "scope": "customer|general",',
      '  "usage": "both|tests|programs",',
      '  "confirmed": true',
      '}',
      'Regeln:',
      '- title/summary muessen fachlich konkret sein (keine Floskeln).',
      '- keywords: 3-8 sinnvolle Stichwoerter.',
      '- category passend waehlen: rule, pattern, warning, example.',
      '- scope: customer, wenn kundenspezifisch; sonst general.',
      '- usage: tests fuer test-/fop-spezifische Regeln, programs fuer reine Programm-/Umsetzungsregeln, both fuer beides.',
      '- confirmed auf true setzen.',
      '- Antworte NUR mit JSON. Kein Markdown. Kein Erklaertext.',
      '',
      'Nutzertext:',
      '{{USER_TEXT}}',
    ].join('\n');
  }

  if (lang === 'es') {
    return [
      'Eres un asistente para clasificacion de learnings en Cucumbergenerator.',
      'Analiza el texto del usuario y devuelve EXACTAMENTE un objeto JSON con este esquema:',
      '{',
      '  "title": "Corto y concreto",',
      '  "summary": "Regla/insight concreto en 1-3 frases",',
      '  "comment": "opcional",',
      '  "keywords": ["kw1", "kw2"],',
      '  "category": "rule|pattern|warning|example",',
      '  "scope": "customer|general",',
      '  "usage": "both|tests|programs",',
      '  "confirmed": true',
      '}',
      'Reglas:',
      '- title/summary deben ser concretos y accionables.',
      '- keywords: 3-8 terminos relevantes.',
      '- category: rule, pattern, warning o example.',
      '- scope: customer para contenido especifico del cliente; si no, general.',
      '- usage: tests para reglas de test/FOP, programs para reglas solo tecnicas, both en los demas casos.',
      '- confirmed debe ser true.',
      '- Devuelve solo JSON. Sin markdown. Sin explicaciones.',
      '',
      'Texto del usuario:',
      '{{USER_TEXT}}',
    ].join('\n');
  }

  if (lang === 'fr') {
    return [
      'Tu es un assistant de classification des learnings dans Cucumbergenerator.',
      'Analyse le texte utilisateur et renvoie EXACTEMENT un objet JSON selon ce schema :',
      '{',
      '  "title": "Court et concret",',
      '  "summary": "Regle/insight concret en 1-3 phrases",',
      '  "comment": "optionnel",',
      '  "keywords": ["kw1", "kw2"],',
      '  "category": "rule|pattern|warning|example",',
      '  "scope": "customer|general",',
      '  "usage": "both|tests|programs",',
      '  "confirmed": true',
      '}',
      'Regles :',
      '- title/summary doivent etre concrets et actionnables.',
      '- keywords : 3-8 termes pertinents.',
      '- category : rule, pattern, warning ou example.',
      '- scope : customer pour du contenu specifique client ; sinon general.',
      '- usage : tests pour les regles test/FOP, programs pour les regles purement techniques, both sinon.',
      '- confirmed doit etre true.',
      '- Retourne uniquement du JSON. Pas de markdown. Pas d\'explication.',
      '',
      'Texte utilisateur :',
      '{{USER_TEXT}}',
    ].join('\n');
  }

  return [
    'You are an assistant for learning classification in Cucumbergenerator.',
    'Analyze the user text and return EXACTLY one JSON object matching this schema:',
    '{',
    '  "title": "Short and concrete",',
    '  "summary": "Concrete rule/insight in 1-3 sentences",',
    '  "comment": "optional",',
    '  "keywords": ["kw1", "kw2"],',
    '  "category": "rule|pattern|warning|example",',
    '  "scope": "customer|general",',
    '  "usage": "both|tests|programs",',
    '  "confirmed": true',
    '}',
    'Rules:',
    '- title/summary must be concrete and actionable.',
    '- keywords: provide 3-8 meaningful terms.',
    '- category: rule, pattern, warning, or example.',
    '- scope: customer for project-specific, otherwise general.',
    '- usage: tests for test/FOP specific rules, programs for program/implementation-only rules, both otherwise.',
    '- set confirmed=true.',
    '- Return JSON only. No markdown. No explanation text.',
    '',
    'User text:',
    '{{USER_TEXT}}',
  ].join('\n');
}
