import type { Scenario } from '../types/gherkin';

export interface CreatedRecord {
  tableRef: string;
  tableName: string;
  searchWord: string;
  scenarioName: string;
  /** True if the search word was auto-generated (should be cleaned up) */
  autoGenerated: boolean;
}

/**
 * Scans all scenarios for the pattern: editorOeffnen NEW → feldSetzen "such"
 * and extracts a list of created records with their search words.
 */
export function extractCreatedRecords(scenarios: Scenario[]): CreatedRecord[] {
  const records: CreatedRecord[] = [];

  for (const scenario of scenarios) {
    let pendingEditor: { tableRef: string; tableName: string } | null = null;

    for (const step of scenario.steps) {
      const a = step.action;

      if (a.type === 'editorOeffnen' && a.command === 'NEW') {
        pendingEditor = { tableRef: a.tableRef, tableName: a.editorName };
      } else if (
        a.type === 'feldSetzen' &&
        a.fieldName.toLowerCase() === 'such' &&
        a.value &&
        pendingEditor
      ) {
        records.push({
          tableRef: pendingEditor.tableRef,
          tableName: pendingEditor.tableName,
          searchWord: a.value,
          scenarioName: scenario.name,
          autoGenerated: a.autoSearchWord === true,
        });
        pendingEditor = null;
      } else if (
        a.type === 'editorOeffnen' ||
        a.type === 'editorOeffnenSuche' ||
        a.type === 'editorOeffnenMenue' ||
        a.type === 'editorSpeichern' ||
        a.type === 'editorSchliessen'
      ) {
        pendingEditor = null;
      }
    }
  }

  return records;
}

/**
 * Generates a search word like "T001KUNDE".
 * Format: T + 3-digit index + table name (uppercase, alphanumeric only).
 * Increments the index if the word already exists.
 */
export function generateSearchWord(
  tableName: string,
  existingWords: string[],
): string {
  const name = tableName
    .toUpperCase()
    .replace(/[^A-Z0-9]/g, '')
    .slice(0, 20);

  if (!name) return '';

  const existing = new Set(existingWords.map((w) => w.toUpperCase()));
  let index = 1;
  while (existing.has(`T${String(index).padStart(3, '0')}${name}`)) {
    index++;
  }
  return `T${String(index).padStart(3, '0')}${name}`;
}

/** Collect all search words used in feldSetzen "such" steps */
export function collectExistingSearchWords(scenarios: Scenario[]): string[] {
  return extractCreatedRecords(scenarios).map((r) => r.searchWord);
}
