/**
 * Tracks record creation across scenarios for search word generation.
 *
 * In abas ERP test scenarios, every newly created record must be assigned a
 * unique "search word" (Suchwort) so that subsequent steps can look it up by
 * name. This module scans scenario steps for the pattern
 * `editorOeffnen NEW → feldSetzen "such"` and extracts the resulting
 * {@link CreatedRecord} list.
 *
 * It also provides {@link generateSearchWord} to mint new search words that
 * follow the project convention (`T001<TABLENAME>`, `T002<TABLENAME>`, …) and
 * guarantee uniqueness within the current feature.
 */
import type { Scenario } from '../types/gherkin';

export interface CreatedRecord {
  tableRef: string;
  tableName: string;
  searchWord: string;
  scenarioName: string;
  /** True if the search word was auto-generated (should be cleaned up) */
  autoGenerated: boolean;
}

/**
 * Scan all scenarios for the `editorOeffnen NEW → feldSetzen "such"` pattern
 * and return a list of created records with their assigned search words.
 *
 * The tracker resets `pendingEditor` whenever it encounters any editor-lifecycle
 * step between the `NEW` open and the `such` field set, preventing false matches
 * across unrelated editor operations.
 *
 * @param scenarios - The scenarios to scan.
 * @returns One {@link CreatedRecord} entry per matched NEW+search-word pair.
 */
export function extractCreatedRecords(scenarios: Scenario[]): CreatedRecord[] {
  const records: CreatedRecord[] = [];

  for (const scenario of scenarios) {
    let pendingEditor: { tableRef: string; tableName: string } | null = null;

    for (const step of scenario.steps) {
      const a = step.action;

      if (a.type === 'editorOeffnen' && a.command === 'NEW') {
        pendingEditor = { tableRef: a.tableRef, tableName: a.editorName };
      } else if (
        a.type === 'feldSetzen' &&
        a.fieldName.toLowerCase() === 'such' &&
        a.value &&
        pendingEditor
      ) {
        records.push({
          tableRef: pendingEditor.tableRef,
          tableName: pendingEditor.tableName,
          searchWord: a.value,
          scenarioName: scenario.name,
          autoGenerated: a.autoSearchWord === true,
        });
        pendingEditor = null;
      } else if (
        a.type === 'editorOeffnen' ||
        a.type === 'editorOeffnenSuche' ||
        a.type === 'editorOeffnenMenue' ||
        a.type === 'editorSpeichern' ||
        a.type === 'editorSchliessen'
      ) {
        pendingEditor = null;
      }
    }
  }

  return records;
}

/**
 * Mint a unique search word for a newly created record.
 *
 * Format: `T<NNN><TABLENAME>` where `NNN` is a zero-padded 3-digit counter
 * and `TABLENAME` is the editor name uppercased with non-alphanumeric characters
 * removed and truncated to 20 characters.
 *
 * The counter starts at 1 and increments until the generated word is not in
 * `existingWords`, ensuring uniqueness within the current feature.
 *
 * @param tableName - The editor/table name to base the search word on.
 * @param existingWords - Already-used search words to avoid duplicating.
 * @returns A unique search word string, or `''` if `tableName` normalises to empty.
 */
export function generateSearchWord(
  tableName: string,
  existingWords: string[],
): string {
  const name = tableName
    .toUpperCase()
    .replace(/[^A-Z0-9]/g, '')
    .slice(0, 20);

  if (!name) return '';

  const existing = new Set(existingWords.map((w) => w.toUpperCase()));
  let index = 1;
  while (existing.has(`T${String(index).padStart(3, '0')}${name}`)) {
    index++;
  }
  return `T${String(index).padStart(3, '0')}${name}`;
}

/**
 * Collect all search words currently set in `feldSetzen "such"` steps
 * across all scenarios. Used as the `existingWords` input to
 * {@link generateSearchWord} to prevent duplicates when auto-generating.
 *
 * @param scenarios - The scenarios to scan.
 * @returns An array of all search word values found.
 */
export function collectExistingSearchWords(scenarios: Scenario[]): string[] {
  return extractCreatedRecords(scenarios).map((r) => r.searchWord);
}
