..!interpreter english translate noabbrev
..*****************************************************************************
.. Name           : allpstart/IS.PRJMMILESTONEANA.YPROJEKT.FX
.. Date           : 09.10.15
.. Version        : 2016r2n01
.. Author         : TS
.. Copyright      : (c) 2015 alltrotec GmbH
.. Functionality  :
..
.. Interface (arguments and their meaning)
..    uses array argument (arg.i)           : no
..    uses name argument  (xpname=value)    : no
..
..    Argument     meaning
..    -------------------------------------------------------------------------
..
.. Program flow   :
...Includes       :
..*****************************************************************************
..
..*****************************************************************************
..
.chart -init
.chart -show ychart 0
..
.continue
