# rabbit-mq
# host (default: erp host name)
RMQ_HOST=erpdemo.abas.local
RMQ_VHOST=abas-iced-erp
# default 5672
RMQ_PORT=5672
# default 15672
RMQ_MANAGEPORT=15672
#RMQ_USER=guest
#RMQ_PASS=guest
# icedaemon
ICE_DATADIR=${MANDANTDIR}/allpstart/allamb/tmp/
ICE_SETUPQUEUE=handshake
