..!interpreter english translate noabbrev
..*****************************************************************************
.. Name           : PDMCENTER.INIT
.. Author         : dsch
.. Verantwortlich : dsch
.. Kontrolle      : cl
.. Functionality  : This I-FILE contains the configuration for the info system 
..                  PDMCENTER and the fop EXPORT.PDM.DATA
..
..include pdm/PDMCENTER.INIT.AUTODESK
..*****************************************************************************
..
.type text xmodelpart  ? _F|defined(U|xmodelpart)
.type text xmodelbom   ? _F|defined(U|xmodelbom)
.type text xmodelresp  ? _F|defined(U|xmodelresp)
.type text xmodelpdmresp  ? _F|defined(U|xmodelpdmresp)
.type text xtastatus   ? _F|defined(U|xtastatus)
.type text xtstatus    ? _F|defined(U|xtstatus)
.type GD2  xderfassvon ? _F|defined(U|xderfassvon)
.type GD2  xderfassbis ? _F|defined(U|xderfassbis)
.type bool xbpartopen  ? _F|defined(U|xbpartopen)
.type bool xbisopen    ? _F|defined(U|xbisopen)
.type bool xbimport    ? _F|defined(U|xbimport)
.type bool xbexport    ? _F|defined(U|xbexport)
.type bool xbusead     ? _F|defined(U|xbusead)
.type bool xbcalledi2  ? _F|defined(U|xbcalledi2)
..
.copy U|xbcalledi2 = G|FALSE
..
..The model for the parts
.formula U|xmodelpart = "9004"
..
..The model for the Boms
.formula U|xmodelbom = "9005"
..
..The model for the Part-Message to PDM
.formula U|xmodelresp = "9006"
..
..The model for the PDMResponse-Message to PDM
.. IF no PDMResponse-Message has to be send then activate the following line 
.. .formula U|xmodelpdmresp = "" 
.formula U|xmodelpdmresp = "9003"
..
.. Precondition for the search - Timespace
.formula U|xderfassvon = "."
.formula U|xderfassbis = "."
..
.formula U|xtastatus  = "2" 
.formula U|xtstatus   = "Bereit zur Verarbeitung"
..
.. Automatically open the Part Screen
.copy U|xbpartopen = G|TRUE
.. Automatically open the infosystem PDMBOMDIFF
.copy U|xbisopen   = G|TRUE
..
..Selection default View
.. Default: Import
.. Only activate import or export
.copy U|xbimport   = G|TRUE
.copy U|xbexport   = G|FALSE
..
.copy U|xbusead = G|FALSE
.. to active a different PDM-System, activate the following line 
.. .copy U|xbusead = G|TRUE
.input "PDMCENTER.INIT.AUTODESK"  ? U|xbusead

