..!interpreter english translate noabbrev
..*****************************************************************************
.. Name           : PDMCENTER.BF
.. Author         : cl
.. Verantwortlich : cl
.. Kontrolle      : mh
.. Functionality  :
..*****************************************************************************
.set trans -
.input "pdm/PDMENDE"
.continue END
..
..*****************************************************************************
!END
.continue
