..!interpreter german translate noabbrev
..*****************************************************************************
.. Name           : ASRUECK.ALLE.FX
.. Date           : 05.12.14
.. Version        : 2014r3n02
.. Author         : chbo
.. Copyright      : (c) 2014 SABA International
.. Functionality  :
..
.. Interface (arguments and their meaning)
..    uses array argument (arg.i)           : no
..    uses name argument  (xpname=value)    : no
..
..    Argument     meaning
..    -------------------------------------------------------------------------
..
.. Program flow   :
...Includes       :
..*****************************************************************************
..
..*****************************************************************************
..
.formel M|augsburg = G|False
.formel M|kassel   = G|False
.formel M|int      = ""
.formel M|ext      = ""
..
.schutz -GESCHUETZT -FELD M|int 0
.schutz -GESCHUETZT -FELD M|ext 0
..
.weiter
