..!interpreter german translate noabbrev
..*****************************************************************************
.. Name           : JPLANUNG.ARTIKEL.ASELEKTION.FX
.. Date           : 13.08.15
.. Version        : 2015r4n01p03
.. Author         : fw
.. Copyright      : (c) 2015 SABA International
.. Functionality  :
..
.. Interface (arguments and their meaning)
..    uses array argument (arg.i)           : no
..    uses name argument  (xpname=value)    : no
..
..    Argument     meaning
..    -------------------------------------------------------------------------
..
.. Program flow   :
...Includes       :
..*****************************************************************************
..
..*****************************************************************************
.hol sperre dazu m|partikel
.fo h|y40aselektion = m|aselektion
.bringe
 
