..!interpreter english translate noabbrev
..*****************************************************************************
.. Name           : HISTORYLOAD.QAKT.FX
.. Date           : 26.03.15
.. Version        : 2015r4n01p03
.. Author         : si/dr
.. Copyright      : (c) 2015 SABA International
.. Functionality  :
..
.. Interface (arguments and their meaning)
..    uses array argument (arg.i)           : no
..    uses name argument  (xpname=value)    : no
..
..    Argument     meaning
..    -------------------------------------------------------------------------
..
.. Program flow   :
...Includes       :
..*****************************************************************************
..
..*****************************************************************************
.continue ? _M|qakt
.box
      !!!very important!!!
don`t load the current data if you want to use
this client as master for a copy to SABAINTERNATIONAL.
.cont
