@persistant
Feature: Editing currency fields
Background:
Given I set the fake date to "2.2.2002"

  Scenario: edit_field_buewekurs   
    Given I'm logged in with password "sy"
    Given I open an editor "BuchungC2" from table "(Entry):(Entry)" with command "NEW" for record ""  
    And I set field "ewbu" to "USD"
    Then field "ewekurs" has value "1.123800"
    Then field "ewkurs" has value "1.123800"
    Then field "eweinh" has value "1"
    Then field "uw" has value "EUR"    
    Then field "iwkurs" has value "1.000000"
    Then field "iwekurs" has value "1.000000"
    Then field "eikurs" has value "1.123800"
    Then field "ieinh" has value "1"
    Then field "ewewu" has value "nein"
    Then field "kursfix" has value "nein"
    
    And I set field "ewekurs" to "0.0"
    Then field "ewekurs" has value "1.123800"
    Then field "ewkurs" has value "1.123800"
    Then field "eweinh" has value "1"
    Then field "uw" has value "EUR"    
    Then field "iwkurs" has value "1.000000"
    Then field "iwekurs" has value "1.000000"
    Then field "eikurs" has value "1.123800"
    Then field "ieinh" has value "1"
    Then field "ewewu" has value "nein"
    Then field "kursfix" has value "nein"
    And I close the current editor  
    
    Given I open an editor "BuchungC3" from table "(Entry):(Entry)" with command "NEW" for record ""  
    Then field "ewbu" has value "EUR"
    Then field "ewekurs" has value "1.000000"
    Then field "ewkurs" has value "1.000000"
    Then field "eweinh" has value "1"
    Then field "uw" has value "EUR"    
    Then field "iwkurs" has value "1.000000"
    Then field "iwekurs" has value "1.000000"
    Then field "eikurs" has value "1.000000"
    Then field "ieinh" has value "1"
    Then field "ewewu" has value "nein" 
    Then field "kursfix" has value "nein" 
    
    And I set field "ewbu" to "USD"
    Then field "ewkurs" has value "1.123800"
    Then field "ewekurs" has value "1.123800"
    Then field "eweinh" has value "1"
    Then field "uw" has value "EUR"    
    Then field "iwkurs" has value "1.000000"
    Then field "iwekurs" has value "1.000000"
    Then field "eikurs" has value "1.123800"
    Then field "ieinh" has value "1"
    Then field "ewewu" has value "nein" 
    Then field "kursfix" has value "nein" 
        
    And I set field "ewekurs" to "1.1"
    Then field "ewkurs" has value "1.100000"
    Then field "ewekurs" has value "1.100000"
    Then field "eweinh" has value "1"
    Then field "uw" has value "EUR"    
    Then field "iwkurs" has value "1.000000"
    Then field "iwekurs" has value "1.000000"
    Then field "eikurs" has value "1.100000"
    Then field "ieinh" has value "1"
    Then field "ewewu" has value "nein"       
    Then field "kursfix" has value "ja"
    And I close the current editor  
    
    Given I open an editor "BuchungC4" from table "(Entry):(Entry)" with command "NEW" for record ""  
    And I set field "ewbu" to "TRL"
    Then field "ewkurs" has value "0.000001"
    Then field "ewekurs" has value "0.775000"
    Then field "eweinh" has value "1000000"
    Then field "uw" has value "EUR"   
    Then field "iwkurs" has value "1.000000"
    Then field "iwekurs" has value "1.000000"
    Then field "eikurs" has value "0.000001"
    Then field "ieinh" has value "1"
    Then field "ewewu" has value "nein"
    Then field "kursfix" has value "nein" 
        
    And I set field "ewekurs" to "1.1"
    Then field "ewkurs" has value "0.000001"
    Then field "ewekurs" has value "1.100000"
    Then field "eweinh" has value "1000000"
    Then field "uw" has value "EUR"    
    Then field "iwkurs" has value "1.000000"
    Then field "iwekurs" has value "1.000000"
    Then field "ieinh" has value "1"
    Then field "ewewu" has value "nein"        
    Then field "kursfix" has value "ja"
    And I close the current editor  
            
Scenario: edit_field_bueikurs   
    Given I'm logged in with password "sy"
    Given I open an editor "BuchungC2" from table "(Entry):(Entry)" with command "NEW" for record ""  
    And I set field "ewbu" to "USD"
    Then field "ewekurs" has value "1.123800"
    Then field "ewkurs" has value "1.123800"
    Then field "eweinh" has value "1"
    Then field "uw" has value "EUR"    
    Then field "iwkurs" has value "1.000000"
    Then field "iwekurs" has value "1.000000"
    Then field "eikurs" has value "1.123800"
    Then field "ieinh" has value "1"
    Then field "ewewu" has value "nein"
    Then field "kursfix" has value "nein"
    
    And I set field "eikurs" to "0.0"
    Then field "ewekurs" has value "1.123800"
    Then field "ewkurs" has value "1.123800"
    Then field "eweinh" has value "1"
    Then field "uw" has value "EUR"    
    Then field "iwkurs" has value "1.000000"
    Then field "iwekurs" has value "1.000000"
    Then field "eikurs" has value "1.123800"
    Then field "ieinh" has value "1"
    Then field "ewewu" has value "nein"
    Then field "kursfix" has value "nein"
    And I close the current editor  
    
    Given I open an editor "BuchungC3" from table "(Entry):(Entry)" with command "NEW" for record ""  
    Then field "ewbu" has value "EUR"
    Then field "ewekurs" has value "1.000000"
    Then field "ewkurs" has value "1.000000"
    Then field "eweinh" has value "1"
    Then field "uw" has value "EUR"    
    Then field "iwkurs" has value "1.000000"
    Then field "iwekurs" has value "1.000000"
    Then field "eikurs" has value "1.000000"
    Then field "ieinh" has value "1"
    Then field "ewewu" has value "nein" 
    Then field "kursfix" has value "nein" 
    
    And I set field "ewbu" to "USD"
    Then field "ewkurs" has value "1.123800"
    Then field "ewekurs" has value "1.123800"
    Then field "eweinh" has value "1"
    Then field "uw" has value "EUR"    
    Then field "iwkurs" has value "1.000000"
    Then field "iwekurs" has value "1.000000"
    Then field "eikurs" has value "1.123800"
    Then field "ieinh" has value "1"
    Then field "ewewu" has value "nein" 
    Then field "kursfix" has value "nein" 
        
    And I set field "eikurs" to "1.1"
    Then field "ewkurs" has value "1.100000"
    Then field "ewekurs" has value "1.100000"
    Then field "eweinh" has value "1"
    Then field "uw" has value "EUR"    
    Then field "iwkurs" has value "1.000000"
    Then field "iwekurs" has value "1.000000"
    Then field "eikurs" has value "1.100000"
    Then field "ieinh" has value "1"
    Then field "ewewu" has value "nein"       
    Then field "kursfix" has value "ja"
    And I close the current editor  
    
    Given I open an editor "BuchungC4" from table "(Entry):(Entry)" with command "NEW" for record ""  
    And I set field "ewbu" to "TRL"
    Then field "ewkurs" has value "0.000001"
    Then field "ewekurs" has value "0.775000"
    Then field "eweinh" has value "1000000"
    Then field "uw" has value "EUR"   
    Then field "iwkurs" has value "1.000000"
    Then field "iwekurs" has value "1.000000"
    Then field "eikurs" has value "0.000001"
    Then field "ieinh" has value "1"
    Then field "ewewu" has value "nein"
    Then field "kursfix" has value "nein" 
        
    And I set field "eikurs" to "1.1"
    Then field "ewkurs" has value "1.100000"
    Then field "ewekurs" has value "1100000.000000"
    Then field "eweinh" has value "1000000"
    Then field "uw" has value "EUR"    
    Then field "iwkurs" has value "1.000000"
    Then field "iwekurs" has value "1.000000"
    Then field "ieinh" has value "1"
    Then field "ewewu" has value "nein"        
    Then field "kursfix" has value "ja"
    And I close the current editor  

#
