..!interpreter english translate noabbrev
..*****************************************************************************
..  FOP-Name       : PRODLIST.COMP
..  Datum          : 01.10.2004
..  Version        :
..  Autor          : jn
..  Verantwortlich : tiwe
..  Kontrolle      : cl
..  Funktion       : Infosystem, Liste der FertigungsvorschlÑge
..                   Fertigungsrueckmeldung
..  Ablauf         :
..*****************************************************************************
.set trans -
.type text xtkomm ? _F|defined(U|xtkomm)
.type text xtsel  ? _F|defined(U|xtsel)
..
.continue AKTU ? G|evtartengl = "BUTTON_AFTER" & G|evtvar = "comp2"
..
.continue BOX1    ? F|empty(M|compz)
.continue BDE     ? M|compz = M|lbdez
.continue         ? F|empty(M|order)
.continue FERTIG  ? F|empty(M|barm)
..
!AENDERN
.formula U|xtkomm = "<(Object)>"+M|barm^id+"<(Edit)>"
.command -wait 'U|xtkomm'
.continue AKTU
..
!FERTIG
.continue FEHLER ? _M|brmerlaub
.formula U|xtkomm = "<(Workorder)>"+M|order^id+"<(Done)>"
.command -wait 'U|xtkomm'
.continue AKTU
..
!AKTU: Tabelle leeren
.input "is/TABLEEREN"
.continue NAECHST          ?  _F|empty(M|kba)
.continue HOLE
..
!NAECHST
.continue BALEEREN         ? F|empty(M|kba)
.select add M|kba
.continue BALEEREN         ? _G|mehr
.select -
.continue HOLE
..
!BALEEREN: BA und M|select leeren
.formula M|kba    = ""
.formula M|select = ""
.continue
..
!HOLE: Tabelle aktualisieren / neu aufbauen
.input "is/HOL.LISTE"
.continue
..
!BOX1
.box
RÅckmeldung nicht mîglich.
.continue
..
!BDE
.box
Vor dem RÅckmelden erst offenen BDE-Datensatz zu diesem BA/AS Åbertragen.
..
.formula U|xtkomm = "<(Infosystem)>PDCTRANSFER<(Call)> ? aschein = " + 'M|order' + " | bstart = 1"
.command -wait 'U|xtkomm'
..Pruefen, ob nun alles gebucht wurde
.formula U|xtsel = "$,,asnr==" + 'M|order^nummer' +";uebertr=1;@gruppe=2.4"
.select pdc 'U|xtsel'
.formula M|compz = M|lcompz ? _G|mehr
.continue

!FEHLER
.error Eine RÅckmeldung ist nicht erlaubt.
.end 1
