..!interpreter english translate noabbrev
..*****************************************************************************
.. Name           : PRODUCTIONSTATUS.FE
.. Author         : tiwe
.. Verantwortlich : tiwe
.. Kontrolle      : cl
.. Functionality  :
..
.. Program flow   :
...Includes       :
..
..*****************************************************************************
.set trans -
.continue BA         ? G|evtartengl = "FIELD_EXIT" & G|evtvar = "ba"
.continue MGENEW     ? G|evtartengl = "FIELD_EXIT" & G|evtvar = "neuemge"
.continue TIMENEW    ? G|evtartengl = "FIELD_EXIT" & G|evtvar = "neuezeit"
.continue ARTIKEL    ? G|evtartengl = "FIELD_EXIT" & G|evtvar = "artikel"
.continue BASIS     ? G|evtartengl = "FIELD_EXIT" & G|evtvar = "basisartikel"
.continue END
..
!BA
.input "is/TABLEEREN"
.continue END            ?  F|empty(M|ba)
.. Betriebsauftrag
.formula M|ba = M|ba^id     ?  F|empty(M|ba^snba)
.. Arbeitsschein
.formula M|ba = M|ba^snba   ? _F|empty(M|ba^snba)
.continue END
..
!MGENEW
.formula M|mgefortschritt = ((M|prodmge + M|neuemge) / M|netmge) *100
..formula M|mgefortschritt = M|mgefortschritt * 100 
.continue END
..
!TIMENEW
.formula M|zeitfortschritt = ((M|istzeit + M|neuezeit) / M|gesdlz) * 100 
..formula M|zeitfortschritt = M|zeitfortschritt * 100
.continue END
!ARTIKEL
.assign M|basisartikel = M|artikel^basisartikel ? _F|empty(M|artikel)
.input "is/TABLEEREN"
.continue END
!BASIS
.formula M|artikel = "" ? _F|empty(M|basisartikel)
.input "is/TABLEEREN"
.continue END
..
..*****************************************************************************
!END
.continue

