..!interpreter english translate noabbrev
..*****************************************************************************
.. Author         : male
.. Verantwortlich : tma
.. Kontrolle      : fwester
.. Functionality  : Init FOP of the Infosystem is/DOWNLOAD
..*****************************************************************************
..!meta M|=is/DOWNLOAD
.set trans -
..
.formula M|resultbase64 = ""
.formula M|exitstatus = 0
.formula M|errormsg = ""
.formula M|encfilesize = 0
.formula M|origfilesize = 0
.formula M|resultbase64 = ""
.continue FILEXT ? G|evtartengl = "FIELD_EXIT" & G|evtvar = "filename"
.continue END
..
..*****************************************************************************
!FILEXT
..*****************************************************************************
.formula M|mimetype = ""
.formula M|abasmimetype = ""
.formula M|fileext = ""
.formula M|defaultfileext = ""
.type integer xi
.formula U|xi = F|strindex(M|filename, ".", -1)
.formula M|fileext = F|substr(M|filename, U|xi+1) ? U|xi<>0 
.continue END
..
..*****************************************************************************
!END
..*****************************************************************************
.continue
