..!interpreter english translate noabbrev
..*****************************************************************************
.. FOP-Name       : FOP.BUINFOSYS.INIT
.. Autor          : fwester
.. Verantwortlich : fwester
.. Kontrolle      : xg
.. Funktion       : Initiale Definition von Variablen
.. Functionality  : Initial definition of variables
..*****************************************************************************
.set trans -
..
.. DECLARATIONS:
.. =============
..
.. References:
.. --------------
.type VID99 xaufrref  ? _F|defined(U|xaufrref)
..
.. Bools:
.. ---------
.type bool xscreen          ? _F|defined(U|xscreen)
.type bool xvisible         ? _F|defined(U|xvisible)
.type A328 xendeaktion      ? _F|defined(U|xendeaktion)
.type bool xallowed         ? _F|defined(U|xallowed)
.type bool xreusewindow     ? _F|defined(U|xreusewindow)
.type bool xdefreuse        ? _F|defined(U|xdefreuse)
.type bool xstringoverflow  ? _F|defined(U|xstringoverflow)
.type bool xposcursor       ? _F|defined(U|xposcursor)
.type bool xisaction        ? _F|defined(U|xisaction)
.type bool xinheader        ? _F|defined(U|xinheader)
.type bool xnovalue         ? _F|defined(U|xnovalue)
..
.. Strings:
.. -----------
.type text xinvisible       ? _F|defined(U|xinvisible)
.type text xparams          ? _F|defined(U|xparams)
.type text xerpcommand      ? _F|defined(U|xerpcommand)
.type text xtitle           ? _F|defined(U|xtitle)
.type text xatitle          ? _F|defined(U|xatitle)
.type text xdelete          ? _F|defined(U|xdelete)
.type text xinsert          ? _F|defined(U|xinsert)
.type text xcursorto        ? _F|defined(U|xcursorto)
.type text xmaskid          ? _F|defined(U|xmaskid)
.type text xtupel           ? _F|defined(U|xtupel)
.type text xtupelname       ? _F|defined(U|xtupelname)
.type text xerrmessage      ? _F|defined(U|xerrmessage)
.type text xerpprintconf    ? _F|defined(U|xerpprintconf)
.type text xmodifying       ? _F|defined(U|xmodifying)
.type text xnomodal         ? _F|defined(U|xnomodal)
.type text xmodal           ? _F|defined(U|xmodal)
.type text xfodialogtype    ? _F|defined(U|xfodialogtype)
.type text xerpcommandneu   ? _F|defined(U|xerpcommandneu)
.type text xcallval         ? _F|defined(U|xcallval)
.type text xtargetname      ? _F|defined(U|xtargetname)
.type text xtargetrow       ? _F|defined(U|xtargetrow)
.type text xadrbuff         ? _F|defined(U|xadrbuff)
.type text xfadr            ? _F|defined(U|xfadr)
.type text xaufrsel         ? _F|defined(U|xaufrsel)
...
.type text xlog6            ? _F|defined(U|xlog6)
.type text xlog5            ? _F|defined(U|xlog5)
.type text xlog4            ? _F|defined(U|xlog4)
.type text xlog3            ? _F|defined(U|xlog3)
.type text xlog2            ? _F|defined(U|xlog2)
.type text xlog1            ? _F|defined(U|xlog1)
.type text xlog0            ? _F|defined(U|xlog0)
.type text xlog             ? _F|defined(U|xlog)
...
.type GL1  XHEADER          ? _F|defined(U|XHEADER)
.type GL1  XASSIGN          ? _F|defined(U|XASSIGN)
.type GL1  XHASH            ? _F|defined(U|XHASH)
.type GL1  XCOLON           ? _F|defined(U|XCOLON)
.type GL1  XPARAMINIT       ? _F|defined(U|XPARAMINIT)
.type GL1  XPARAMSEP        ? _F|defined(U|XPARAMSEP)
.type GL1  XPOINT           ? _F|defined(U|XPOINT)
..
.. Integer:
.. -----------
.type integer XNODB2        ? _F|defined(U|XNODB2)
.type integer XNODB1        ? _F|defined(U|XNODB1)
.type integer XNEW          ? _F|defined(U|XNEW)
.type integer XINFOSYS      ? _F|defined(U|XINFOSYS)
.type integer XMAXLEN       ? _F|defined(U|XMAXLEN)
.type integer xsubstlen     ? _F|defined(U|xsubstlen)
.type integer xfatal        ? _F|defined(U|xfatal)
.type integer xerror        ? _F|defined(U|xerror)
.type integer xadrrow       ? _F|defined(U|xadrrow)
..
.. INITIALIZATIONS:
.. ================
..
.. References:
.. --------------
..
.. Bools:
.. ---------
.. If TRUE, the callparameter is allowed
.copy U|xallowed = G|FALSE
.. If TRUE, the callparameter is visible in the menu
.copy U|xvisible = G|FALSE
.. If TRUE and errors occur, program will report to screen and abort
.copy U|xscreen = G|TRUE
.. If TRUE and a dialog with ID of mask already exists, the window will be reused
.copy U|xdefreuse = G|TRUE
.copy U|xreusewindow = U|xdefreuse
.. If TRUE, GUI command string will be too long
.copy U|xstringoverflow = G|FALSE
..
.. Strings:
.. -----------
.. Constants command characters for building gui commands and fo programs
.copy U|XPOINT = "."
.copy U|XPARAMSEP = "|"
.copy U|XPARAMINIT = "?"
.copy U|XCOLON = ":"
.copy U|XHASH = "#"
.copy U|XASSIGN = "="
.copy U|XHEADER = "0"
.. Default parameter tupel of gui commands which defines their invisible execution
.copy U|xinvisible = "[invisible]=1"
.. GUI command actions
.copy U|xcursorto = "[pos]"
.copy U|xinsert = "[insert]"
.copy U|xdelete = "[delete]"
.. ID for the windows the infosystem starts in
.copy U|xmaskid = ""
.. Outgoing parameter as tupel string
.copy U|xtupel = ""
.. All outgoing parameter as command string
.copy U|xparams = ""
.. Strings for erp command
.copy U|xerpprintconf = ""
.copy U|xerpcommand = ""
.copy U|xerpcommandneu = ""
.. String for error message
.copy U|xerrmessage = ""
.. Messages for logging and boxes
.set trans +
.continue ISTITEL ? U|xsource^dnr = 65
.continue ISTITEL ? _F|defined(M|grbez) ; _F|defined(M|sucherw)
.set trans +
.copy U|xtitle = F|formatstr("Info zu {1} {2}", M|grbez, M|sucherw)
.copy U|xatitle = F|formatstr("Aktion zu {1} {2}", M|grbez, M|sucherw)
.continue ETITEL
!ISTITEL
.copy U|xtitle = F|formatstr("Info zu {1} {2}", U|xsource^grbez, U|xsource^sucherw)
.copy U|xatitle = F|formatstr("Aktion zu {1} {2}", U|xsource^grbez, U|xsource^sucherw)
!ETITEL
.copy U|xlog0 = "Der Aufrufparameter ist nicht ausfÅhrbar, weil: {1}!"
.copy U|xlog1 = "Er nicht aktiv ist"
.copy U|xlog2 = "Sein Arbeitsbereich {1} nicht erlaubt ist"
.set trans -
.. Fo options for dialog type
.copy U|xnomodal = "PARALLEL"
.copy U|xmodal = "WARTEN"
.copy U|xmodifying = "FENSTER"
.copy U|xfodialogtype = "FENSTER"
..
.. Integer:
.. -----------
.. Length of the print configuration string
.copy U|xsubstlen = 0
.copy U|XINFOSYS = 65
.copy U|XNEW = 14
.copy U|XNODB1 = 13
.copy U|XNODB2 = 52
.copy U|XMAXLEN = F|typelength("T")
..*****************************************************************************
!END
.continue
