<?xml version="1.0" encoding="UTF-8"?>
<!--
********************************************************************************
Modul Name      : infosysdiff_varnames.dtd
Datum           : 10.01.2008
Version         : 2008r1
Autor           : fwester
Verantwortlich  : fwester
Kontrolle       : 
********************************************************************************
-->
<!ELEMENT INFOSYS (HEADER+, TABLE+)>
<!ELEMENT HEADER (FIELDS*)>
<!ELEMENT TABLE (FIELDS*)>
<!ELEMENT FIELDS (FIELD*)>
<!ELEMENT FIELD EMPTY>
<!ATTLIST FIELD
   name    CDATA #REQUIRED
   program (true|false) "false" 
>
