..!interpreter english translate noabbrev
..*****************************************************************************
.. Author         : male
.. Verantwortlich : tma
.. Kontrolle      : fwester
.. Functionality  : Field exit FOP of the field "filename"
..                  in the Infosystem is/UPLOAD
..*****************************************************************************
..!meta M|=is/UPLOAD
.set trans -
..
.continue END   ?  F|empty(M|filename)
.continue ERR03 ? _F|fileexists(M|filename)
.. the destination file has to empty
.continue ERR03 ?  F|filesize(M|filename) <> 0
.. the destination file has to be in the rmtmp directory
.continue ERR03 ? _F|regmatch(M|filename, "^rmtmp/X.*TMP$")
.formula  M|errormsg   = ""
.formula  M|exitstatus = 0
.continue END
..
..*****************************************************************************
!ERR03
..*****************************************************************************
.formula M|exitstatus = 3
.set trans +
.formula M|errormsg = "Zugriff verweigert."
.set trans -
.continue END ? M|normalexit
.error -message 'M|errormsg'
.end 1
..
..*****************************************************************************
!END
..*****************************************************************************
.continue
