..!interpreter english translate noabbrev
..*****************************************************************************
.. Author         : male
.. Verantwortlich : tma
.. Kontrolle      : fwester
.. Functionality  : Init FOP of the Infosystem is/UPLOAD
..*****************************************************************************
..!meta M|=is/UPLOAD
.set trans -
..
.formula M|exitstatus = 0
.formula M|errormsg = ""
.continue END
..
..*****************************************************************************
!END
..*****************************************************************************
.continue
