..!interpreter english translate noabbrev
..*****************************************************************************
.. Name           : CONSWAREHOUSE.FE
.. Author         : tiwe
.. Verantwortlich : tiwe
.. Kontrolle      : cl
.. Function       : Feldaustritt / Field exit
..
..*****************************************************************************
.. Eventhandling
..*****************************************************************************
.set trans -
.continue ANALYSE  ? G|evtvar = "analyse"
.continue MELDUNG  ? G|evtvar = "meldung"
.continue DATVON   ? G|evtvar = "datvon"
.continue DATBIS   ? G|evtvar = "datbis"
.continue ENDE
..
!ANALYSE
.copy M|meldung  = G|false  ?  M|analyse
.copy M|meldung  = G|true   ?  _M|analyse
.formula P|maskkontextfop = "MELDUNG"  ?  M|meldung
.formula P|maskkontextfop = "ANALYSE"  ? _M|meldung
.input "is/TABLEEREN"
.continue ENDE
!MELDUNG
.copy M|analyse = G|false  ? M|meldung
.copy M|analyse = G|true   ? _M|meldung
.formula P|maskkontextfop = "MELDUNG"  ? _M|analyse
.formula P|maskkontextfop = "ANALYSE"  ?  M|analyse
.input "is/TABLEEREN"
.continue ENDE
!DATVON:
.input "is/TABLEEREN"
.continue ENDE
!DATBIS
.input "is/TABLEEREN"
.continue ENDE
..*****************************************************************************
..Programmende
..*****************************************************************************
!ENDE
.continue

