..!interpreter english translate noabbrev
..*****************************************************************************
.. Name           : ABRUFZENTRALE.TAB.INIT
.. Autor          : mh
.. Verantwortlich : mh
.. Kontrolle      :
.. Functionality  : Initialize temporary  fields for one row's forecast evaluation
..*****************************************************************************
.set trans -
..
.continue DEFINED  ?  F|defined(U|xnabdat)
..
.type GD    xnabdat
.type GD    xhorizont
..
.type MP9.3 xkw0mge
.type MP9.3 xkw1mge
.type MP9.3 xkw2mge
.type MP9.3 xkw3mge
.type MP9.3 xkw4mge
.type MP9.3 xkw5mge
..
.type MP9.3 xwt1mge
.type MP9.3 xwt2mge
.type MP9.3 xwt3mge
.type MP9.3 xwt4mge
.type MP9.3 xwt5mge
.type MP9.3 xwt6mge
.type MP9.3 xwt7mge
.type MP9.3 xwt8mge
.type MP9.3 xwt9mge
.type MP9.3 xwt10mge
.type MP9.3 xwt11mge
.type MP9.3 xwt12mge
.type MP9.3 xwt13mge
.type MP9.3 xwt14mge
.type MP9.3 xwt15mge
.type MP9.3 xwt16mge
.type MP9.3 xwt17mge
.type MP9.3 xwt18mge
.type MP9.3 xwt19mge
.type MP9.3 xwt20mge
.type MP9.3 xwt21mge
.type MP9.3 xwt22mge
.type MP9.3 xwt23mge
.type MP9.3 xwt24mge
.type MP9.3 xwt25mge
.type MP9.3 xwt26mge
.type MP9.3 xwt27mge
.type MP9.3 xwt28mge
..
.type MP9.3 xtag0mge
.type MP9.3 xtag1mge
.type MP9.3 xtag2mge
.type MP9.3 xtag3mge
.type MP9.3 xtag4mge
.type MP9.3 xtag5mge
.type MP9.3 xtag6mge
..
.type MP9.3 xmonat0mge
.type MP9.3 xmonat1mge
.type MP9.3 xmonat2mge
.type MP9.3 xmonat3mge
.type MP9.3 xmonat4mge
.type MP9.3 xmonat5mge
..
!DEFINED
..
..
.formula U|xkw0mge = 0.000
.formula U|xkw1mge = 0.000
.formula U|xkw2mge = 0.000
.formula U|xkw3mge = 0.000
.formula U|xkw4mge = 0.000
.formula U|xkw5mge = 0.000
..
.formula U|xwt1mge = 0.000
.formula U|xwt2mge = 0.000
.formula U|xwt3mge = 0.000
.formula U|xwt4mge = 0.000
.formula U|xwt5mge = 0.000
.formula U|xwt6mge = 0.000
.formula U|xwt7mge = 0.000
.formula U|xwt8mge = 0.000
.formula U|xwt9mge = 0.000
.formula U|xwt10mge = 0.000
.formula U|xwt11mge = 0.000
.formula U|xwt12mge = 0.000
.formula U|xwt13mge = 0.000
.formula U|xwt14mge = 0.000
.formula U|xwt15mge = 0.000
.formula U|xwt16mge = 0.000
.formula U|xwt17mge = 0.000
.formula U|xwt18mge = 0.000
.formula U|xwt19mge = 0.000
.formula U|xwt20mge = 0.000
.formula U|xwt21mge = 0.000
.formula U|xwt22mge = 0.000
.formula U|xwt23mge = 0.000
.formula U|xwt24mge = 0.000
.formula U|xwt25mge = 0.000
.formula U|xwt26mge = 0.000
.formula U|xwt27mge = 0.000
.formula U|xwt28mge = 0.000
..
.formula U|xtag0mge = 0.000
.formula U|xtag1mge = 0.000
.formula U|xtag2mge = 0.000
.formula U|xtag3mge = 0.000
.formula U|xtag4mge = 0.000
.formula U|xtag5mge = 0.000
.formula U|xtag6mge = 0.000
..
.formula U|xmonat0mge = 0.000
.formula U|xmonat1mge = 0.000
.formula U|xmonat2mge = 0.000
.formula U|xmonat3mge = 0.000
.formula U|xmonat4mge = 0.000
.formula U|xmonat5mge = 0.000
..
..*****************************************************************************
!END
.continue
