..!interpreter english translate noabbrev
..*****************************************************************************
.. Name           : CREDITNOTE.KEDI.FE
.. Author         : mh
.. Verantwortlich : mh
.. Kontrolle      : 
.. Functionality  : Field exit for edi message field.
..                  Validate if edi message is a credit note. 
..*****************************************************************************
..!meta M|=dfue/CREDITNOTE
.set trans -
..
.type P53 edi
.copy U|edi = M|kedi
..
.input "is/KOPFLEEREN"
.make screen line --
..
.continue END ? F|empty(U|edi)
.. 
.copy M|kedi = U|edi
.copy M|kedinachr = U|edi^edinachr
.copy M|kganr = U|edi^ganr
..
.continue NOCRED ? 'M|kedi^edinachraz(L=":")'<>"(CreditNote)"
..
..*****************************************************************************
!END
.continue
..
.. Show "errors" only as notes. 
.. Would produce duplicate error boxes if user is quick with start button.
.. 
..
!NOCRED
.cursor kedi 0
.note Das ist keine Gutschriftenanzeige!
.end 0
