..!interpreter english translate
..
.. Programmkopf
.continue INI
..*******************************************************************************************************
..*
..*  Programmname : DRUCK.AB
..*
..*  Autor        : Ozan Kesim
..*
..*  Generiert am : 17.02.04
..*  Funktion     : Druckt IHSS fÅr EDI-AuftragsbestÑtigung
..*
..*  Bemerkung    : Ist Unterprogramm von DRUCK.VORGANG
..*******************************************************************************************************
.set trans +
!INI
.type text xtfotmp
.type integer  xi1zaehl
.continue START
..
!START
.up
.page 1
..
..
EDI-ID: 'H|num   '                                                    Mandant: 'mandant '
vom   : 'H|ddatei '               IHSS fÅr EDI-AuftragsbestÑtigung    Datum  : 'datum   '
Zeit  : 'H|zdatei '                                                   Seite  : 'seite   '
------------------------------------------------------------------------------------------
.continue MAIN0
..
!MAIN0
.select line
.continue ENDE0       ? _mehr
..
.continue MUNBI                                  ?  H|text1 / "*UNBI*"
.continue MUNHI                                  ?  H|text1 / "*UNHI*"
.continue MBGMI                                  ?  H|text1 / "*BGMI*"
.continue MRFH1                                  ?  H|text1 / "*RFH1*"
.continue MRFH2                                  ?  H|text1 / "*RFH2*"
.continue MDAH1                                  ?  H|text1 / "*DAH1*"
.continue MSUP1                                  ?  H|text1 / "*SUP1*"
.continue MSUP2                                  ?  H|text1 / "*SUP2*"
.continue MBUY1                                  ?  H|text1 / "*BUY1*"
.continue MBUY2                                  ?  H|text1 / "*BUY2*"
.continue MIV1                                   ?  H|text1 / "*IV1*"
.continue MDPA1                                  ?  H|text1 / "*DPA1*"
.continue MDPA2                                  ?  H|text1 / "*DPA2*"
.continue MLIN1                                  ?  H|text1 / "*LIN1*"
.continue MRFL1                                  ?  H|text1 / "*RFL1*"
.continue MRFL2                                  ?  H|text1 / "*RFL2*"
.continue MART1                                  ?  H|text1 / "*ART1*"
.continue MART2                                  ?  H|text1 / "*ART2*"
.continue MQTY1                                  ?  H|text1 / "*QTY1*"
.continue MALC1                                  ?  H|text1 / "*ALC1*"
.continue MPRI1                                  ?  H|text1 / "*PRI1*"
.continue MUNZI                                  ?  H|text1 / "*UNZI*"
.continue MAIN0
..
!MUNBI
?Absenderbezeichnung                           : 'H|text3' ? 'H|text3'<>""
?EmpfÑngerbezeichnung                          : 'H|text6' ? 'H|text6'<>""
.type date xdatum
.assign T|xdatum = 'H|text9'
?Dateierstellungsdatum                         : 'T|xdatum'               ?  mehr & 'T|xdatum'<>""
?Dateierstellungsdatum                         : 'H|text9'    ? _mehr & 'H|text9'<>""
?Dateierstellungszeit                          : 'H|text10' ? 'H|text10'<>""
?öbertragungsnummer-alt                        : 'H|text12' ? 'H|text12'<>""
?öbertragungsnummer-neu                        : 'H|text13' ? 'H|text13'<>""
.type date xdatum
.assign T|xdatum = 'H|text15'
?öbertragungsdatum                             : 'T|xdatum'               ?  mehr & 'T|xdatum'<>""
?öbertragungsdatum                             : 'H|text15'    ? _mehr & 'H|text15'<>""
.continue MAIN0
..
!MUNHI
?Referenznummer                                : 'H|text3' ? 'H|text3'<>""
?Nachrichtentyp                                : 'H|text4' ? 'H|text4'<>""
?Versionsnummer und Freigabenummer             : 'H|text5' ? 'H|text5'<>""
?Belegart                                      : 'H|text6' ? 'H|text6'<>""
?Verwaltende Organisation                      : 'H|text7' ? 'H|text7'<>""
.continue MAIN0
..
!MBGMI
?Belegnummer                                   : 'H|text3' ? 'H|text3'<>""
.type date xdatum
.assign T|xdatum = 'H|text4'
?Belegdatum                                    : 'T|xdatum'               ?  mehr & 'T|xdatum'<>""
?Belegdatum                                    : 'H|text4'    ? _mehr & 'H|text4'<>""
?Funktion                                      : 'H|text5' ? 'H|text5'<>""
.continue MAIN0
..
!MRFH1
?WÑhrung, verschl.                             : 'H|text20' ? 'H|text20'<>""
.continue MAIN0
..
!MRFH2
.continue MAIN0
..
!MDAH1
.type date xdatum
.assign T|xdatum = 'H|text5'
?Referenzdatum 1                               : 'T|xdatum'               ?  mehr & 'T|xdatum'<>""
?Referenzdatum 1                               : 'H|text5'    ? _mehr & 'H|text5'<>""
.type date xdatum
.assign T|xdatum = 'H|text6'
?Referenzdatum 2                               : 'T|xdatum'               ?  mehr & 'T|xdatum'<>""
?Referenzdatum 2                               : 'H|text6'    ? _mehr & 'H|text6'<>""
.continue MAIN0
..
!MFTXH
.continue MAIN0
..
!MSUP1
------------------------------------------------------------------------------------------
?Lieferanten-GLN-Nummer                        : 'H|text3' ? 'H|text3'<>""
?Lieferantennummer beim Kunden                 : 'H|text4' ? 'H|text4'<>""
?Lieferanten-USt-IdNr                          : 'H|text9' ? 'H|text9'<>""
.continue MAIN0
..
!MSUP2
.continue MAIN0
..
!MBUY1
------------------------------------------------------------------------------------------
?Kunden-GLN-Nummer                             : 'H|text3' ? 'H|text3'<>""
?Kundennummer beim Lieferanten                 : 'H|text4' ? 'H|text4'<>""
?Kunden-USt-IdNr                               : 'H|text9' ? 'H|text9'<>""
?Kundenkontakt                                 : 'H|text10' ? 'H|text10'<>""
.continue MAIN0
..
!MBUY2
.continue MAIN0
..
!MIV1
------------------------------------------------------------------------------------------
?RechnungsempfÑnger-GLN-Nummer                 : 'H|text3' ? 'H|text3'<>""
?RechnungsempfÑnger-Nummer beim Lieferanten    : 'H|text4' ? 'H|text4'<>""
?RechnungsempfÑnger-USt-IdNr                   : 'H|text9' ? 'H|text9'<>""
.continue MAIN0
..
!MDPA1
------------------------------------------------------------------------------------------
?WarenempfÑnger-GLN-Nummer                     : 'H|text3' ? 'H|text3'<>""
?WarenempfÑnger-Nummer beim Lieferanten        : 'H|text4' ? 'H|text4'<>""
?WarenempfÑnger -Werk                          : 'H|text6' ? 'H|text6'<>""
?WarenempfÑnger-Abladestelle                   : 'H|text7' ? 'H|text7'<>""
?WarenempfÑngerkontakt                         : 'H|text10' ? 'H|text10'<>""
.continue MAIN0
..
!MDPA2
.continue MAIN0
..
!MLIN1
------------------------------------------------------------------------------------------
?Positionsnummer                               : 'H|text4' ? 'H|text4'<>""
.continue MAIN0
..
!MFTXL
.continue MAIN0
..
!MRFL1
?Auftragsnummer                                : 'H|text5' ? 'H|text5'<>""
.type date xdatum
.assign T|xdatum = 'H|text8'
?Liefer-/Lieferscheindatum                     : 'T|xdatum'               ?  mehr & 'T|xdatum'<>""
?Liefer-/Lieferscheindatum                     : 'H|text8'    ? _mehr & 'H|text8'<>""
?Lieferabrufnummer                             : 'H|text12' ? 'H|text12'<>""
.continue MAIN0
..
!MRFL2
?Werk-Kunde                                    : 'H|text12' ? 'H|text12'<>""
?Abladestelle des Kunden                       : 'H|text13' ? 'H|text13'<>""
.continue MAIN0
..
!MART1
------------------------------------------------------------------------------------------
?GTIN-Artikelnummer                            : 'H|text3' ? 'H|text3'<>""
?Kundenartikelnummer                           : 'H|text4' ? 'H|text4'<>""
?Lieferantenartikelnummer                      : 'H|text5' ? 'H|text5'<>""
?Artikelbezeichnung 1                          : 'H|text10' ? 'H|text10'<>""
.continue MAIN0
..
!MART2
.continue MAIN0
..
!MQTY1
?Menge                                         : 'H|text3' ? 'H|text3'<>""
?Mengeneinheit                                 : 'H|text4' ? 'H|text4'<>""
?Auftrags- bzw. LAB-Menge                      : 'H|text7' ? 'H|text7'<>""
?Auftrags-Mengeneinheit                        : 'H|text8' ? 'H|text8'<>""
.continue MAIN0
..
!MALC1
?Prozentsatz, verschl.                         : 'H|text8' ? 'H|text8'<>""
?Prozentsatz                                   : 'H|text9' ? 'H|text9'<>""
.continue MAIN0
..
!MPRI1
?Preis                                         : 'H|text4' ? 'H|text4'<>""
?Ma·einheit fÅr den Preis                      : 'H|text8' ? 'H|text8'<>""
?Verkaufspreis, Nettowert                      : 'H|text12' ? 'H|text12'<>""
?WÑhrung                                       : 'H|text19' ? 'H|text19'<>""
.continue MAIN0
..
!MUNZI
.continue MAIN0
..
!ENDE0
.continue
..
