..!interpreter english translate noabbrev
..*****************************************************************************
.. Name           : EDI.DO.OSEARCH.INIT
.. Author         : mh
.. Verantwortlich : mh
.. Kontrolle      : carue
.. Functionality  : Initializes an edi message for object search
..                  Clears previous error codes
..                  Initializes status with 4: Did not complete object search
..                  EDI.DO.OSEARCH.FINISH sets status 3 if no errors were detected
..*****************************************************************************
.set trans -
..
.. Required: edi message in H buffer
.continue NOEDI ? _F|defined(H|edinachr)
.continue NOTYPE ? F|empty(H|edinachr)
..
.. Lock Edi message!
.select lock edifact 'H|id'
.continue NOLOCK ? _G|mehr ; _G|gesperrt
..
.. Clear error codes
.formula H|fcode = 0
..
.. Block import processing unless OSEARCH finishes
.formula H|status = 4
.rewrite
..
..*****************************************************************************
!END
.continue
..
..
!NOLOCK
.error Das Sperren des EDI-Datensatzes 'H|nummer' ist gescheitert.
.end 1
..
!NOEDI
.error Fehler bei Start der Objektsuche: Kein EDI-Datensatz angegeben.
.end 1
..
!NOTYPE
.error Fehler bei Start der Objektsuche: EDI-Datensatz 'H|nummer' hat keinen Nachrichten-Eintrag.
.end 1
