..!interpreter english translate noabbrev
..!meta M|=dfue/EDICOLINVOICEPRINT
..*****************************************************************************
.. Name           : EDICOLINVOICEPRINT.KEDI.FE
.. Author         : mh
.. Verantwortlich : mh
.. Kontrolle      : dsch
.. Functionality  : Field exit for edi message field 
..*****************************************************************************
.set trans -
..
.type P53 edi
.copy U|edi = M|kedi
..
.input "is/KOPFLEEREN"
.make screen line --
..
.assign M|kprotokoll = ""
..
.continue END ? F|empty(U|edi)
.. 
.copy M|kedi = U|edi
.. 
.add U|edi
.formula M|kprotokoll = "(VDA)" 
.formula M|kprotokoll = "(EDIFACT)" ? D|nachrtyp="INVOIC"
.assign M|kreempfaenger = D|idkunderab
.copy M|kuebnr = D|uebnr
.copy M|kedinachr = D|edinachr
.add
..
.continue NOINVOI ? 'M|kedi^edinachraz(L=":")'<>"(Invoice)"
..
..*****************************************************************************
!END
.continue
..
..
!NOINVOI
.cursor kedi 0
.error Das ist keine EDI-Rechnung!
.end 1

