..!interpreter english translate noabbrev
..!meta M|=dfue/FORECASTCONFIG
..*****************************************************************************
.. Name           : FORECASTCONFIG.SE.FOCHECK.SUB
.. Author         : mh
.. Verantwortlich : mh
.. Kontrolle      :
.. Functionality  :
..*****************************************************************************
.set trans -
.. 
.formula U|fostdpath = "dfue/" + 'U|foprogramm'
.formula U|foindivpath = F|foppath('U|foprogramm')
..
.formula M|kbstdfoprogramme = G|true    ?  F|fileexists('U|fostdpath')
.formula M|kbindivfoprogramme = G|true  ?  F|fileexists('U|foindivpath') & 'U|foindivpath' <> 'U|fostdpath'
.. 
..*****************************************************************************
!END
.continue
