..!interpreter english translate noabbrev
..!meta M|=dfue/FORECASTCONFIG
..*****************************************************************************
.. Name           : FORECASTCONFIG.KBUEXPORT.BB
.. Author         : mh
.. Verantwortlich : mh
.. Kontrolle      :
.. Functionality  :
..*****************************************************************************
.set trans - 
.. 
.formula M|kexportdatei = ""
.. 
..*****************************************************************************
!END
.continue
