..!interpreter english translate noabbrev
..!meta M|=dfue/PRICAT
..*****************************************************************************
.. Name           : PRICAT.AUSWAHL.FE
.. Author         : mh
.. Verantwortlich : mh
.. Kontrolle      :
.. Functionality  : Validate selection on exit auswahl and on every "start"
...Includes       :
..*****************************************************************************
.set trans - 
..
.. Initialise table on parameter change
.make screen line -- 
.. 
.. Selection bar = leave % in M|auswahl
.continue END ? M|auswahl/"%*"
.continue RANGE ? M|auswahl/"*!*"
..
.. Show parts parameter (only on field exit)
.formula M|auswahl = M|select  ?  G|evtartengl="FIELD_EXIT"
.. 
.. Validate parts parameter 
.continue END ? F|isvalue('M|auswahl', "N2")
.continue END ? F|isvalue('M|auswahl', "SW2")
.continue ID2NUM ? F|isvalue('M|auswahl', "ID2")
.continue NOPARTS
..
!RANGE
.type text from
.type text to
.formula U|from = M|auswahl<<"!"
.formula U|to = M|auswahl>>"!"
.continue END  ?  F|empty(U|from) ; F|empty(U|to)
.continue END  ? +U|from<+U|to
.continue END  ?  U|from<=U|to & +U|from=+U|to
.formula M|auswahl = U|to + "!" + U|from
.continue END
..
.. Human readable auswahl
!ID2NUM
.type P2 parts
.assign U|parts = M|auswahl
.formula M|auswahl = U|parts^nummer   ? _F|sysinfo(18)^swziffern
.formula M|auswahl = U|parts^such     ?  F|sysinfo(18)^swziffern
..
..*****************************************************************************
!END
.continue
.. 
.. 
!NOPARTS
.error Mit der Angabe 'M|auswahl' wird kein Artikel gefunden.
.end 1
