..!interpreter english translate noabbrev
..!meta M|=dfue/PRICAT
..*****************************************************************************
.. Name           : PRICAT.KUNDE.FE
.. Author         : mh
.. Verantwortlich : mh
.. Kontrolle      :
.. Functionality  : Field exit event for field customer (is)kunde
..                  gets customer price group from customer database
...Includes
..  include dfue/PRICAT.INIT
..*****************************************************************************
.set trans -
.. 
.. 
.. kunderab might be parameter for Sales tab in Product (klprg)
.. Only initialize on changing the customer
.formula M|kunderab = ""
.. 
.. Changing the customer starts a new price list
.input "PRICAT.INIT"
..
..*****************************************************************************
!END
.continue
