..!interpreter english translate noabbrev
..!meta M|=dfue/PRICAT
..*****************************************************************************
.. Name           : PRICAT.INIT
.. Author         : mh
.. Verantwortlich : mh
.. Kontrolle      :
.. Functionality  : Initialize new price list process
...Includes
..  include dfue/DFUE.GET.PROTOK 
..*****************************************************************************
.set trans -
..
.make screen line -- 
..
.formula M|idprialt    = ""
.formula M|uebnrprialt = "0"
.formula M|edinr       = ""
.formula M|dateiname   = ""
..
.. Initialize with empty customer
.continue END ? F|empty(M|kunde)
..
..!meta H|=P0:1
.select customer 'M|kunde^id' 
.. kunderab might be parameter for Sales tab in Product
.formula M|kunderab = H|rab ? F|empty(M|kunderab)
..
.. Fields for DFUE.GET.PROTOK
.type P109:2 xedinachr
.type bool xediaktiv
.type text xediuebnr
.type text xextedi
..
.. Check if PRICAT is active an get latest transmit number
.formula U|xedinachr = "2116"
.input "DFUE.GET.PROTOK"
.continue NOPROT ? _U|xediaktiv
.formula M|uebnrprialt = U|xediuebnr
.formula M|idprialt    = U|xextedi
..
.select -
..
..*****************************************************************************
!END
.continue
..
.. 
!NOPROT
.error Das Versenden der Artikelpreisliste ist nicht aktiv.
.end 1
