..!interpreter english translate noabbrev
..*****************************************************************************
.. Name           : TAXRATES.INIT
.. Author         : mh
.. Verantwortlich : mh
.. Kontrolle      :
.. Functionality  :
..*****************************************************************************
.set trans -
..
.type P58 taxcode ? _F|defined(U|taxcode)
.. 
.select taxcode "$,,;@gruppe=11;@ordnung=kopf^nummer"
.continue END ? _G|mehr
..
!TAXCODE
.assign U|taxcode = H|id
.input TAXRATES.INDEX
.type text xSteuerSatz.itax ? _F|defined(U|xSteuerSatz.itax)
.type real xStSatz.itax ? _F|defined(U|xStSatz.itax)
.type real xGWW.itax ? _F|defined(U|xGWW.itax)
.type real xStBetragG.itax ? _F|defined(U|xStBetragG.itax)
.type real xReBetragBruttoG.itax ? _F|defined(U|xReBetragBruttoG.itax)
.type real xReBetragNettoG.itax ? _F|defined(U|xReBetragNettoG.itax)
.type real xNet.itax ? _F|defined(U|xNet.itax)
.type real xNettoG.itax ? _F|defined(U|xNettoG.itax)
.type real xGSt.itax ? _F|defined(U|xGSt.itax)
.type real xWarenWert.itax ? _F|defined(U|xWarenWert.itax)
.type real xAbschlag.itax ? _F|defined(U|xAbschlag.itax)
.type real xZuschlag.itax ? _F|defined(U|xZuschlag.itax)
.type real xStBetrag.itax ? _F|defined(U|xStBetrag.itax)
.type real xStBasis.itax ? _F|defined(U|xStBasis.itax)
.type real xReBetragNetto.itax ? _F|defined(U|xReBetragNetto.itax)
.type real xReBetragBrutto.itax ? _F|defined(U|xReBetragBrutto.itax)
.. 
.formula U|xSteuerSatz.itax = 'U|taxrate'
..
.select taxcode
.continue TAXCODE ? G|mehr
.. 
..*****************************************************************************
!END
.continue
