..!interpreter english translate noabbrev
..*****************************************************************************
.. Name           : TSB.INIT
.. Author         : mh
.. Verantwortlich : mh
.. Kontrolle      :
.. Functionality  : Parameters for calling the "TSB-Generator" from VW AG 
..                  to generate:
..                  - Transport Bill VDA 4939  (Transportbeleg VDA 4939)
..                  - and Shipping Bill 4939  (Sendungsbeleg VDA 4939)
..                  - Global Transport Labels
..*****************************************************************************
.set trans -
..
.. @deprecated TSB 3.5 is used in automatic mode; display is no longer needed
.type text xttsbdisplay  ? _F|defined(U|xttsbdisplay)
.formula U|xttsbdisplay="xvfbtest:9.0"
..
.. @deprecated TSB 3.5 is used infosystem TSBPRINT instead of EDILS
.type bool xbimmertsbinedils  ? _F|defined(U|xbimmertsbinedils)
.copy U|xbimmertsbinedils = G|false
..
..*****************************************************************************
..
.. Configure file names (used in infosystem TSBPRINT)
.. 
.. Known version based names
.. TSB 2.0  directory for output of generated tsb files: "out"
.. TSB 2.0  does not created gtl files!
.. TSB 3.X  directory for output of generated tsb files: "out_tsb"
.. TSB 3.X  directory for output of generated gtl files: "out_gtl"
.. TSB 3.2..3.3  suffix for generatred gtl files: ""_GTL.pdf""
.. TSB 3.5  suffix for generated gtl files: "_GTL_0.pdf"
.. TSB 3.5  suffix for generated tsb fiels: "_VDA4939.pdf"
..
.type text xttsbverzeichnis  ? _F|defined(U|xttsbverzeichnis)
.type text xtvdaverz  ? _F|defined(U|xtvdaverz)
.type text xtvdasuffix  ? _F|defined(U|xtvdasuffix)
.type text xttsbverz  ? _F|defined(U|xttsbverz)
.type text xttsbsuffix  ? _F|defined(U|xttsbsuffix)
.type text xtgtlverz  ? _F|defined(U|xtgtlverz)
.type text xtgtlsuffix  ? _F|defined(U|xtgtlsuffix)
.. 
.formula U|xttsbverzeichnis = "win/tsb"
.formula U|xtvdaverz = "in"
.formula U|xtvdasuffix = ".VDA"
.formula U|xttsbverz = "out_tsb"
.formula U|xttsbsuffix = "_VDA4939.pdf"
.formula U|xtgtlverz = "out_gtl"
.formula U|xtgtlsuffix = "_GTL_0.pdf"
.. 
..*****************************************************************************
.. 
.. Configure how long to wait for TSB tool to generate pdf files when 
.. doing collective print with infosystem TSBPRINT.
.. 
.type integer xisleep ? _F|defined(U|xisleep)
.type integer ximaxwait ? _F|defined(U|ximaxwait)
.. 
.formula U|xisleep = 1
.formula U|ximaxwait = 5
.. 
..*****************************************************************************
!END
.continue
