..!interpreter english translate noabbrev
..*****************************************************************************
.. Name           : TSBPRINT.VKSPEDNR.FE
.. Author         : mh
.. Verantwortlich : mh
.. Kontrolle      :
.. Functionality  : Field exit for shipping order, remove old results, 
..                  define new target file names for internal use,
..                  and expected file names in tsb utility.
..*****************************************************************************
..!meta M|=dfue/TSBPRINT
.set trans -
..
.. Initialize file names
.formula M|kihssdatei = ""
.formula M|kimportdatei = ""
.formula M|kvdadateiname = ""
.formula M|kvdadatei = ""
.formula M|ktsbdatei = ""
.formula M|kgtldatei = ""
.. 
.copy M|kbihssvorhanden = G|false
.copy M|kbimportvorhanden = G|false
.copy M|kbvdavorhanden = G|false
.copy M|kbtsbvorhanden = G|false
.copy M|kbgtlvorhanden = G|false
.. 
.. Done if no no shipping order is given
.continue END ? F|empty(M|vkspednr)
.. 
.. Set file name for ihss file and import file
.type text xtihssdatei
.type text xtimportdatei
.file -screen -tempname U|xtihssdatei
.file -screen -tempname U|xtimportdatei
.formula M|kihssdatei = U|xtihssdatei
.formula M|kimportdatei = U|xtimportdatei
..
.. Construct expected file names for tsb utility
.formula M|kvdadateiname = "VDA4913." + 'M|vkspednr^nummer'
.formula M|kvdadatei = M|ktsbverzeichnis + "/" + M|kvdaverz + "/" + M|kvdadateiname + M|kvdasuffix
.formula M|ktsbdatei = M|ktsbverzeichnis + "/" + M|ktsbverz + "/" + M|kvdadateiname + M|ktsbsuffix 
.formula M|kgtldatei = M|ktsbverzeichnis + "/" + M|kgtlverz + "/" + M|kvdadateiname + M|kgtlsuffix 
..
.. Remove previously generated files  
.system 'F|formatstr("rm -f {1}", M|ktsbdatei)' background
.system 'F|formatstr("rm -f {1}", M|kgtldatei)' background
..
..*****************************************************************************
!END
.continue
