..!interpreter english translate noabbrev
.. ---------------------------------------------------------
.. FOP-Name             : LAHI.CL
.. Autor                : ns
.. Verantwortlich       : tiwe
.. Kontrolle            : cl
.. Funktion             : Kopffelder l”schen
.. ---------------------------------------------------------
.set trans -
..
.. Gruppe
.assign M|kggruppe    = ""
.assign M|kgans       = ""
.assign M|kgstr       = ""
.assign M|kglakenn    = ""
.assign M|kgplz       = ""
.assign M|kgnort      = ""
.assign M|kgtelefon   = ""
.assign M|kgemail     = ""
.assign M|kgfax       = ""
.. Lager
.assign M|kllager     = ""
.assign M|klans       = ""
.assign M|klstr       = ""
.assign M|kllakenn    = ""
.assign M|klplz       = ""
.assign M|klnort      = ""
.assign M|kltelefon   = ""
.assign M|klemail     = ""
.assign M|klfax       = ""
.assign M|kldispo     = ""
.assign M|klauslief   = ""
.assign M|kllnullm    = ""
.. Platz
.assign M|kplatz      = ""
.assign M|kpname      = ""
.assign M|kleer       = ""
.assign M|kdispo      = ""
.assign M|kauslief    = ""
.assign M|kzuplatz    = ""
.assign M|kabplatz    = ""
.. ---------------------------------------------------------
!END
.continue
