..!interpreter english translate noabbrev
.. ---------------------------------------------------------
.. FOP-Name             : LAHI.SH
.. Autor                : ns
.. Verantwortlich       : tiwe
.. Kontrolle            : cl
.. Funktion             : Kopffelder fÅllen
.. ---------------------------------------------------------
.set trans -
..
.. Gruppe
.copy M|kggruppe    = M|tggruppe
.copy M|kgans       = M|tgans
.copy M|kgstr       = M|tgstr
.copy M|kglakenn    = M|tglakenn
.copy M|kgplz       = M|tgplz
.copy M|kgnort      = M|tgnort
.copy M|kgtelefon   = M|tgtelefon
.copy M|kgemail     = M|tgemail
.copy M|kgfax       = M|tgfax
.. Lager
.copy M|kllager     = M|tllager
.copy M|klans       = M|tlans
.copy M|klstr       = M|tlstr
.copy M|kllakenn    = M|tllakenn
.copy M|klplz       = M|tlplz
.copy M|klnort      = M|tlnort
.copy M|kltelefon   = M|tltelefon
.copy M|klemail     = M|tlemail
.copy M|klfax       = M|tlfax
.copy M|kldispo     = M|tldispo
.copy M|klauslief   = M|tlauslief
.copy M|kllnullm    = M|tllnullm
.. Platz
.copy M|kplatz      = M|tplatz
.copy M|kpname      = M|tpname
.copy M|kleer       = M|tleer
.copy M|kdispo      = M|tdispo
.copy M|kauslief    = M|tauslief
.copy M|kzuplatz    = M|tzuplatz
.copy M|kabplatz    = M|tabplatz
.. ---------------------------------------------------------
!END
.continue
