..!interpreter english translate noabbrev
.. ---------------------------------------------------------
.. FOP-Name             : LAHI.LL
.. Autor                : ns
.. Verantwortlich       : tiwe
.. Kontrolle            : cl
.. Funktion             : Datenfelder der Zeilenlupe fÅllen
.. ---------------------------------------------------------
.set trans -
..
.assign M|tllager     = 1|id
.formula M|tlans         = 1|ans
.formula M|tlstr         = 1|str
.formula M|tllakenn      = 1|lakenn
.formula M|tlplz         = 1|plz
.formula M|tlnort        = 1|nort
.formula M|tltelefon     = 1|telefon
.formula M|tlemail       = 1|email
.formula M|tlfax         = 1|fax
.formula M|tldispo       = 1|dispo
.formula M|tlauslief     = 1|auslief
.formula M|tllnullm      = 1|lnullm
.. ---------------------------------------------------------
!END
.continue
