..!interpreter english translate noabbrev
..*****************************************************************************
.. Name              : EXPLORER.FE
.. Author            : tiwe
.. Verantwortlich    : tiwe
.. Kontrolleur       : cl
.. Functionality	 : Feldaustritt
..                     Vorbelegung des Suchbegriffs Åber Verzeichnisse und KÅrzel
..                     in Dateien suchen Åber indatsuch
..*****************************************************************************
.. Variablendefinition
..*****************************************************************************
.set trans -
.type text xtslash ? _F|defined(U|xtslash)
.type text xtcmd   ? _F|defined(U|xtcmd)
.type GL60 xtindatsuch ? _F|defined(U|xtindatsuch) 
..*****************************************************************************
.. Eventhandling
..*****************************************************************************
.continue FELDAUS ? G|evtartengl = "FIELD_EXIT"
.continue ENDE
..***************************************
.. Feldaustritt
..***************************************
!FELDAUS
.continue SUCHBEG ? G|evtvar = "suchbegriff"
.continue VERZ1   ? G|evtvar = "verzeichnis1"
.continue KUERZEL ? G|evtvar = "kuerzel"
.continue PFAD    ? G|evtvar = "pfad1"
.continue GREP    ? G|evtvar = "indatsuch"
.continue VERGL   ? G|evtvar = "vergleichen"
.continue REKURS  ? G|evtvar = "rekursiv"
.continue ENDE
!REKURS: rekursives Suchen
.protection M|vergleichen ? M|rekursiv
.protection -reset M|vergleichen ? _M|rekursiv 
.formula M|suchbegriff = ""
.formula M|such1 = ""
.continue ENDE
!VERGL
.continue VERGLJA ? M|vergleichen
.continue VERGLNO ? _M|vergleichen
!VERGLJA
.select screen header
.select screen line
.continue ERR04 ? _G|mehr
.formula P|maskkontextfop  = "VERGLEICHEN"
.formula U|xtslash = "/" 
.formula M|pfad2 = M|pfadvor6 + M|verzeichnis1 + U|xtslash ? _F|empty(M|verzeichnis1)
.formula M|pfad2 = M|pfadvor6 + M|verzeichnis1             ?  F|empty(M|verzeichnis1)
.continue NOSICH ? _M|sichverw
.formula M|sichpfad = M|pfadvor6
.continue NOVERZ   ? F|empty(M|sichverz)
.formula M|sichpfad = M|sichpfad + M|sichverz + "/"
!NOVERZ
!NOSICH
.continue NOCOPY ? F|empty(M|pfadvor7)
.formula M|kopiepfad = M|pfadvor7 + M|verzeichnis1 + U|xtslash ? _F|empty(M|verzeichnis1) 
.formula M|kopiepfad = M|pfadvor7 + M|verzeichnis1             ?  F|empty(M|verzeichnis1) 
!NOCOPY
.input "sy/EXPLORER.BA"
.continue ENDE
!VERGLNO
.formula P|maskkontextfop  = ""
.formula M|pfad2 = ""
.make screen line --
.continue ENDE
!VERZ1
.copy   M|vergleichen = G|false
.formula M|indatsuch    = ""
.formula U|xtslash = "/"  ? _F|empty(M|verzeichnis1)
.formula U|xtslash = ""   ?  F|empty(M|verzeichnis1)
.formula M|pfad1 = M|pfad1  + 'M|verzeichnis1' + 'U|xtslash'
..prÅfen, ob es den Pfad auch gibt
.formula U|xtcmd = "ls -ltr " + 'M|pfad1'
.system 'U|xtcmd' background
.continue ERR06 ? _G|mehr
.formula M|such1 = "ls -ltr " + 'M|pfad1' + " | grep -i " + 'M|suchbegriff' 
.formula M|such1 = "ls -ltr " + 'M|pfad1'                                   ? F|empty(M|suchbegriff)
.formula M|such1 = "ls -ltr " + 'M|pfad2' + " | grep -i " + 'M|suchbegriff' ? M|vergleichen
.cursor suchbegriff 0
.input "is/TABLEEREN"
.copy M|bbackup = G|false
.continue ENDE
!SUCHBEG
.continue NOREK ? _M|rekursiv
.continue REK   ? M|rekursiv
!NOREK
.formula U|xtslash = "/"  ? _F|empty(M|verzeichnis1)
.formula U|xtslash = ""   ?  F|empty(M|verzeichnis1)
.formula M|such1 = "ls -ltr " + 'M|pfad1' + " | grep -i " + 'M|suchbegriff' 
.formula M|such1 = "ls -ltr " + 'M|pfad1'                                   ? F|empty(M|suchbegriff)
.copy M|vergleichen = G|false
.input "is/TABLEEREN"
.copy M|bbackup = G|false
.continue ENDE
!REK
.continue ERR05 ? F|empty(M|suchbegriff)
.formula M|such1  = "find " + 'M|pfad1' + " -iname *" + 'M|suchbegriff' + "* -ls"
.copy M|vergleichen = G|false
.input "is/TABLEEREN"
.copy M|bbackup = G|false
.continue ENDE
!KUERZEL
.formula M|verzeichnis1 = ""
.formula M|suchbegriff  = ""
.formula M|indatsuch    = ""
.input "is/TABLEEREN"
.copy M|bbackup = G|false
.continue K1 ? M|kuerzel = M|kuerzelvor1
.continue K2 ? M|kuerzel = M|kuerzelvor2
.continue K3 ? M|kuerzel = M|kuerzelvor3
.continue K4 ? M|kuerzel = M|kuerzelvor4
.continue K5 ? M|kuerzel = M|kuerzelvor5
.continue K6 ? M|kuerzel = M|kuerzelvor6
.continue K7 ? M|kuerzel = M|kuerzelvor7 
.continue ERR01
!K1
.formula M|pfad1= M|pfadvor1
.formula M|such1 = "ls -ltr " + 'M|pfad1'
.continue ENDE
!K2
.formula M|pfad1 = M|pfadvor2
.formula M|such1 = "ls -ltr " + 'M|pfad1'
.continue ENDE
!K3
.formula M|pfad1 = M|pfadvor3
.formula M|such1 = "ls -ltr " + 'M|pfad1'
.continue ENDE
!K4
.formula M|pfad1 = M|pfadvor4
.formula M|such1 = "ls -ltr " + 'M|pfad1'
.continue ENDE
!K5
.formula M|pfad1 = M|pfadvor5
.formula M|such1 = "ls -ltr " + 'M|pfad1'
.continue ENDE
!K6
.formula M|pfad1 = M|pfadvor6
.formula M|such1 = "ls -ltr " + 'M|pfad1'
.continue ENDE
!K7
.formula M|pfad1 = M|pfadvor7
.formula M|such1 = "ls -ltr " + 'M|pfad1'
.continue ENDE
!PFAD
.formula M|such1 = "ls -ltr " + 'M|pfad1'
.input "is/TABLEEREN"
.continue ENDE
!GREP
..prÅfen, ob es Zeilen gibt
.continue ERR03 ? F|empty(M|indatsuch)
.formula U|xtindatsuch = G|dblquote + M|indatsuch + G|dblquote
.select screen header
.select screen line
.continue ERR02 ? _G|mehr
!LOOPGRE
.continue NEXTLIN ? M|tzeilenicon = M|iconverzzu
.formula U|xtcmd = "grep " + 'U|xtindatsuch' + " " + 'M|tkomplett' + " >rmtmp/EXPLORER.GREP"
.system 'U|xtcmd' background
.formula M|ttreffer = M|icontreffer  ? G|mehr
.formula M|ttreffer = ""             ? _G|mehr
.continue NEXTLIN ? F|empty(M|tkomplett2)
.formula U|xtcmd = "grep " + 'U|xtindatsuch' + " " + 'M|tkomplett2' + " >rmtmp/EXPLORER.GREP2"
.system 'U|xtcmd' background
.formula M|ttreffer2 = M|icontreffer  ? G|mehr
.formula M|ttreffer2 = ""             ? _G|mehr
!NEXTLIN
.continue VIEWALL ? _M|nurtrefferzeigen
.continue VIEWTRE ? M|nurtrefferzeigen
!VIEWTRE 
.. Grep hat keinen Treffer, die Zeile Lîschen
.make screen line -o   ? M|ttreffer <> M|icontreffer
..wenn letzte Zeile keinen Treffer hat
.continue ENDE        ? M|aktzeile < 1
.continue LOOPGRE     ? M|ttreffer <> M|icontreffer
.. Grep hat Treffer, die Zeile stehen lassen
.select screen line   ? M|ttreffer = M|icontreffer
.continue LOOPGRE ? G|mehr
.continue ENDE
!VIEWALL
.select screen line 
.continue LOOPGRE ? G|mehr
.continue ENDE
..*****************************************************************************
.. Programmende
..*****************************************************************************
!ENDE
.continue
..*****************************************************************************
.. Fehler
..*****************************************************************************
!ERR01:
.error KÅrzel nicht gefunden.
.formula M|kuerzel = ""
.cursor kuerzel 0
..
.end 1
!ERR02: keine Zeile zum greppen
.error Keine Dateien in der Tabelle vorhanden
.end 1
..
!ERR03: Feld indatsuch ist leer, da macht ein grep keinen Sinn
.end 1
!ERR04: Vergleichen geht nur bei gefÅllter Tabelle
.error Vergleichen geht nur bei gefÅllter Tabelle
..
.copy M|vergleichen = G|false
.end 1
!ERR05: Rekursives suchen ohne Suchbegriff
.error Rekursives Suchen: Suchbegriff eingeben
.cursor suchbegriff
.end 1
!ERR06: Pfad existiert nicht
.error Der Pfad existiert nicht!
.end 1 

