..!interpreter english translate noabbrev
..*****************************************************************************
.. FOP-Name       : BILANZ.PERIOD1.FE
.. Autor          : male
.. Verantwortlich : cl
.. Kontrolle      : mh
.. Funktion       : Feldaustritts-FOP fÅr erste Periode in fb/BILANZ/BILANZNACH
.. Functionality  : Field exit FOP of first period's fields in fb/BILANZ/BILANZNACH
..*****************************************************************************
..
..
..*****************************************************************************
..
.set trans -
..
.continue END ? G|evtvar <> "jahr1" & G|evtvar <> "amon1" & G|evtvar <> "emon1"
.input "fb/KBFORMBILGUV.EV"
.formula M|jahr2   = F|prevfy(M|jahr1)
.formula M|amon2   = M|amon1
.formula M|emon2   = M|emon2
.formula M|adatum2 = F|fystartdate(M|jahr2, M|amon2)
.formula M|edatum2 = F|fyenddate(M|jahr2, M|emon2)
.continue END
..
..*****************************************************************************
!END
..*****************************************************************************
.continue
