..!interpreter declaration english translate
..*****************************************************************************
..  FOP-Name       : BUJ.INIT
..  Autor          : male
..  Verantwortlich : cl
..  Kontrolle      : mh
..  Funktion       : Infosystem, Buchungsjournal, Maskeneintritt
..                   Wird auch fuer das Infosystem STBUJ verwendet
..
.. include WAEHRUNG.INI
..*****************************************************************************
..
.set trans -
..
.input WAEHRUNG.INI
..
.copy M|buwaehr  = G|inland
.copy M|auswaehr = G|inland
.copy M|bukreis  = G|bukreis
.formula   M|kurs     = 1.0
.formula   M|von      = F|fystartdate(F|getfy(G|datum))
.copy M|bis     = G|datum
.select period 'M|von' 'M|bis'
.formula   M|anfm = G|amonat
.formula   M|endm = G|emonat
.formula   M|anfj = G|ajahr
.formula   M|endj = G|ejahr
..
.formula   M|konsol = "(97)"
.formula   M|buart  = "(70)"
..
..Check wether fixed asset management is enabled
.load 0 company "$,gruppe=18;@gruppe=18"
.formula   M|anl  = 0|anl
.formula   M|kore = 0|kost
.formula   M|stbu = 0|stbu
.formula   M|konz = 0|konz
.load 0
..
.continue ERROR1 ? _M|stbu & (M|istyp = 1)
.continue FINENT ?  M|istyp = 0
..
.formula   M|buart     = "(83)"
.copy M|buartalle = G|false
.formula   M|vkzart    = "(73)"
.protection koart   ? _M|kore
..
..*****************************************************************************
!FINENT: Infosystem is BUJ
..*****************************************************************************
.protection buartalle ? _M|stbu
.protection buart     ? _M|stbu
.protection konsol    ? _M|konz
..
.continue
..
..
..*****************************************************************************
!ERROR1: no statistical entries available
..*****************************************************************************
.error Statistische Buchungen sind nicht aktiviert.
.end 1
