..!interpreter english translate noabbrev
..*****************************************************************************
.. FOP-Name       : CASHMGMT.SELECT.INIT
.. Autor          : male
.. Verantwortlich : cl
.. Kontrolle      : mh
.. Funktion       : Initialisierung der Selektion
.. Functionality  :
.. include fb/CASHMGMT.CONFIG
.. include fb/CASHMGMT.INIT.TAX.PERIODS
.. include fb/CASHMGMT.MESSAGES
.. include fb/CASHMGMT.MESSAGES.DEF
..*****************************************************************************
..
.set trans -
..
.. init messages
.input "fb/CASHMGMT.MESSAGES.DEF"
.input "fb/CASHMGMT.MESSAGES"
..
.type text   xtselect
.type PS94:1 xpoutcurr xppostcurr
.type PS81:4 xpsetofbooks
.. the period
.type integer    xiperiod
.. Discounted value
.type RU     xrvalue
.type RU     xrdiscount
.. Cash discount rate
.type real   xrdiscrate
.. select single document
.type VID99  xpdocument
.. Data type
.type AZS20300 xttype
.type AS304  xeintercompany
.type AZS20302 xcategory
.type B1     xbintercompany
.type GD     xddate
.type GD     xddocdate
.type GD     xdvaldate
.. calculated due dates (header and item)
.type GD     xdhterm
.type GD     xdtterm
.. due date manually set? (Faelligkeit manuell fixiert?)
.type bool  xbmterm
.. terms of payment (Zahlungsbedingung)
.type P12:8 xpzbed
.. terms of payment code (Zahlungsbedingungsschluessel)
.type P66:4 xpzbedschl
.type P66:6 xpzbedvert
.type R     xrexratefixed
.type bool  xbexratefixed
.type AS7   xepurchsales
.type AS192 xeinout
.type text  xtout
.. grace period (Karenztage)
.type integer   xikarenztage
..
.type text  xtinitfop ? _F|defined(U|xtinitfop)
..
.. flags for en-/disabling data
.type bool xbselobcash ? _F|defined(U|xbselobcash)
.type bool xbseloi     ? _F|defined(U|xbseloi)
.type bool xbsellioek  ? _F|defined(U|xbsellioek)
.type bool xbselreoek  ? _F|defined(U|xbselreoek)
.type bool xbselliovk  ? _F|defined(U|xbselliovk)
.type bool xbselreovk  ? _F|defined(U|xbselreovk)
.type bool xbselbvor   ? _F|defined(U|xbselbvor)
.type bool xbselvat    ? _F|defined(U|xbselvat)
.type bool xbselppay   ? _F|defined(U|xbselppay)
.type bool xbselcredit ? _F|defined(U|xbselcredit)
..
.input "fb/CASHMGMT.CONFIG"
..
.. Start date
.type GD   xdstartdate
.. Maximum period
.type integer  ximaxperiod
.type AS225 xiperiodtype
.type integer  xitufactor
..
.formula U|xiinitfop = "fb/CASHMGMT.SELECT.INIT.BATCH" ? F|empty(U|xtinitfop)
..
.input 'U|xtinitfop'
..
.input "fb/CASHMGMT.INIT.TAX.PERIODS"
..
.copy U|xpliqkber = U|xppayconfig^lqkbereich
.copy U|xparexcluded = U|xpszenario^verdkbereich
.copy U|xpustvaform = U|xpszenario^ustvaakt
.copy U|xpzahllastpos = U|xpszenario^ustpossteuer
.copy U|xpzahllastposzeile = U|xpszenario^ustpossteuerzn
.copy U|xustvazeitraum = U|xpszenario^ustvazeitraum
.continue SETOUT
..
..*****************************************************************************
!SETOUT
..*****************************************************************************
.input "DATEI.F"
.output new 'U|xtout'
.continue END
..
..*****************************************************************************
!END
..*****************************************************************************
.continue

