..!interpreter english translate noabbrev
.continue END ? F|defined(U|xbisinitialized)
..*****************************************************************************
.. FOP-Name       : CASHMGMT.IS.COMMON.INIT
.. Autor          : male
.. Verantwortlich : cl
.. Kontrolle      : mh
.. Funktion       : Allgemeine Initialisierungen
.. Functionality  : Common initializations
.. include fb/CASHMGMT.IS.COMMON.INIT0
.. include fb/CASHMGMT.INIT.PERIODS
..*****************************************************************************
..
.set trans -
..
.type bool xbisinitialized
..
.input "fb/CASHMGMT.IS.COMMON.INIT0"
..
..*****************************************************************************
!GETMAXP: Try to detect array size (maximum period index)
..*****************************************************************************
.formula U|xi = 0
..*****************************************************************************
!GMPLOOP
..*****************************************************************************
.formula U|xi = U|xi + 1
.continue INIT ? _F|defined(M|perstart.U|xi)
.formula M|maxper = U|xi
.continue GMPLOOP
..
..*****************************************************************************
!INIT
..*****************************************************************************
.copy U|xiperiodtype = M|zeiteinheit
.formula   U|ximaxperiod = M|maxper
.input "fb/CASHMGMT.INIT.PERIODS"
.formula U|xi = 0
..*****************************************************************************
!LOOP
..*****************************************************************************
.formula U|xi = U|xi + 1
.continue END ? U|xi > M|maxper
.copy M|perstart.U|xi = U|xpstart.U|xi
.copy M|perend.U|xi = U|xpend.U|xi
.formula   M|perend0 = M|perstart1 - 1 ? U|xi = 1 & F|defined(M|perend0)
.continue LOOP ? _F|defined(M|perbez.U|xi)
.continue ND ? U|xiperiodtype = "(Day)"
.continue NW ? U|xiperiodtype = "(Week)"
.continue NM ? U|xiperiodtype = "(Month)"
.continue NQ ? U|xiperiodtype = "(Quarter)"
.continue NY ? U|xiperiodtype = "(Year)"
.formula   M|perbezb.U|xi = ""
.continue LOOP
!ND
.formula   M|perbez.U|xi = M|perstart.U|xi//1
.continue LOOP
!NW
.formula   M|perbez.U|xi = F|tostring(F|tovalue(F|tostring(M|perstart.U|xi), "GW2"))
.continue LOOP ? F|empty(M|perend.U|xi)
.formula   U|xt = F|tostring(F|tovalue(F|tostring(M|perend.U|xi), "GW2"))
.formula   M|perbez.U|xi = M|perbez.U|xi + " - " + U|xt ? U|xt <> M|perbez.U|xi
.continue LOOP
!NM
.formula   M|perbez.U|xi = F|tovalue(F|expr("(" + F|tostring(F|month(M|perstart.U|xi)) + ")"), "A203")
.continue LOOP ? F|empty(M|perend.U|xi)
.formula   U|xt = F|tovalue(F|expr("(" + F|tostring(F|month(M|perend.U|xi)) + ")"), "A203")
.formula   M|perbez.U|xi = M|perbez.U|xi + " - " + U|xt ? U|xt <> M|perbez.U|xi
.continue LOOP
!NQ
.formula   M|perbez.U|xi = "Q" + 'F|condexpr(F|month(M|perstart.U|xi) > 9, 4, F|condexpr(F|month(M|perstart.U|xi) > 6, 3, F|condexpr(F|month(M|perstart.U|xi) > 3, 2, 1)))'
.continue LOOP ? F|empty(M|perend.U|xi)
.formula   U|xt = "Q" + 'F|condexpr(F|month(M|perend.U|xi) > 9, 4, F|condexpr(F|month(M|perend.U|xi) > 6, 3, F|condexpr(F|month(M|perend.U|xi) > 3, 2, 1)))'
.formula   M|perbez.U|xi = M|perbez.U|xi + " - " + U|xt ? U|xt <> M|perbez.U|xi
.continue LOOP
!NY
.formula   M|perbez.U|xi = 'F|year(M|perstart.U|xi)'
.continue LOOP ? F|empty(M|perend.U|xi)
.formula   U|xt = 'F|year(M|perend.U|xi)'
.formula   M|perbez.U|xi = M|perbez.U|xi + " - " + U|xt ? U|xt <> M|perbez.U|xi
.continue LOOP
..
..*****************************************************************************
!END
..*****************************************************************************
.continue

