..!interpreter english translate noabbrev
..*****************************************************************************
.. FOP-Name       : KBFORMBILGUV.CMPAR.INIT
.. Autor          : male
.. Verantwortlich : cl
.. Kontrolle      : mh
.. Funktion       : Initialisierung der Vergleichskontenbereiche im Kopf
..*****************************************************************************
..
.set trans -
..
.. index of account range
.type integer xicmpkb ? _F|defined(U|xicmpkb)
..
.formula U|xicmpkb = 0
..*****************************************************************************
!CMPAR: Loop over account ranges for comparison
..*****************************************************************************
.formula U|xicmpkb = U|xicmpkb + 1
.continue END ? U|xicmpkb > M|maxcmpkb
.formula M|cmpkb.U|xicmpkb = ""
.continue CMPAR
..
..*****************************************************************************
!END
..*****************************************************************************
.input "fb/KBFORMBILGUV.CMPVALUES.INIT"
.continue
