..!interpreter english translate noabbrev
..*****************************************************************************
.. FOP-Name       : KBFORMBILGUV.CMPVALUES.INIT
.. Datum          : 20.03.2007
.. Version        : 1
.. Autor          : male
.. Verantwortlich : cl
.. Kontrolle      : mh
.. Funktion       : Initialisierung der Vergleichswerte im Kopf
..
.. Schnittstelle (Parameter und ihre Bedeutung)
..   verwendet Arrayparameter (arg.i)          : nein
..   verwendet Namensparameter (xpname=wert)   : nein
..
..   Parameter    Bedeutung
..   ---------------------------------------------------------
..   xp...        ...
..
.. Ablauf         :
..
.. Functionality  :
..
.. Interface (arguments and their meaning)
..   uses array argument (arg.i)           : no
..   uses name argument  (xpname=value)    : no
..
..   Argument     meaning
..   ---------------------------------------------------------
..   xp...        ...
..
.. Program flow   :
...Includes       :
..*****************************************************************************
..
..
..*****************************************************************************
..
.set trans -
..
.. index of account range
.type integer xicmpkb   ? _F|defined(U|xicmpkb)
.. name of the variable with the value
.type text xtcmpvar ? _F|defined(U|xtcmpvar)
..
.formula U|xicmpkb = 0
..*****************************************************************************
!CMPKB: Loop over account ranges for comparison
..*****************************************************************************
.formula U|xicmpkb = U|xicmpkb + 1
.continue END ? U|xicmpkb > M|maxcmpkb
..
.formula U|xizraum = 0
..*****************************************************************************
!CMPAR: Comparison account range touched
..*****************************************************************************
.formula U|xizraum = U|xizraum + 1
.continue CMPKB ? U|xizraum > M|maxperiod
.formula U|xtcmpvar = "cmp" + 'U|xicmpkb' + "p" + 'U|xizraum'
.formula M|.U|xtcmpvar = 0.00
.continue CMPAR
..
..*****************************************************************************
!END
..*****************************************************************************
.continue
