..!interpreter english translate noabbrev
..*****************************************************************************
.. FOP-Name       : LIQPLANDETAILS.INIT
.. Autor          : male
.. Verantwortlich : cl
.. Kontrolle      : mh
.. Funktion       :
.. Functionality  :
.. include fb/CASHMGMT.IS.COMMON.INIT
..*****************************************************************************
..
.set trans -
..
.input "fb/CASHMGMT.IS.COMMON.INIT"
..
.copy M|perstart = M|perstart.M|periodevon
.copy M|perend = M|perend.M|periodebis
..
.continue END
..
..*****************************************************************************
!END
..*****************************************************************************
.continue

