..!interpreter english translate noabbrev
..*****************************************************************************
.. Author         : male
.. Verantwortlich : cl
.. Kontrolle      : mh
.. Functionality  : load initial calculation scheme
.. include fb/LIQPLAN.SCHEMA
.. include fb/LIQPLAN.ROW.INSERT
..*****************************************************************************
..
.set trans -
..
.input "is/ABASFARBEN.DEF"
..
.type IP3 xschemapos   ? _F|defined(U|xschemapos)
.type AZS20300 xttype  ? _F|defined(U|xttype)
.type AS7 xepurchsales ? _F|defined(U|xepurchsales)
.type IP2 xitype       ? _F|defined(U|xitype)
.type B1 xbrowsum      ? _F|defined(U|xbrowsum)
.type B1 xbcatpossible ? _F|defined(U|xbcatpossible)
.type B1 xbicpossible  ? _F|defined(U|xbicpossible) 
.type text xtcolor     ? _F|defined(U|xtcolor)
.type text xtcondition ? _F|defined(U|xtcondition)
.type integer xitreelevel  ? _F|defined(U|xitreelevel)
.type text xtdummy     ? _F|defined(U|xtdummy)
..
.formula U|xitreelevel = 0
..
.select from "fb/LIQPLAN.SCHEMA" U|xtdummy^
..*****************************************************************************
!LOOP
..*****************************************************************************
..pos # name # p/s # type # row sum # category possible # intercompany possible # color # condition
.select from "fb/LIQPLAN.SCHEMA" U|xschemapos # U|xttype # U|xepurchsales # U|xitype # U|xbrowsum # U|xbcatpossible # U|xbicpossible # U|xtcolor # U|xtcondition #
.continue END  ? _G|mehr
.continue LOOP ? _F|condexpr(F|empty(U|xtcondition), G|TRUE, F|eval(U|xtcondition))
.formula U|xtcolor = F|condexpr(F|empty(U|xtcolor), "", F|eval("U|" + U|xtcolor))
.input "fb/LIQPLAN.ROW.INSERT"
.continue LOOP
..
..*****************************************************************************
!END
..*****************************************************************************
.continue
