..!interpreter english translate noabbrev
..*****************************************************************************
.. FOP-Name       : LSS2.INIT
.. Autor          : male
.. Verantwortlich : cl
.. Kontrolle      : mh
.. Funktion       : Maske initialisieren
.. Functionality  :
..*****************************************************************************
..
.set trans -
..
.make screen line --
.formula M|asollsum    = 0
.formula M|ahabensum   = 0
.formula M|vkzsollsum  = 0
.formula M|vkzhabensum = 0
.formula M|esollsum    = 0
.formula M|ehabensum   = 0
.formula M|esollsum2   = 0
.formula M|ehabensum2  = 0
.formula M|ganfsal     = 0
.formula M|vkzsal      = 0
.formula M|gessum      = 0
.formula M|gessum2     = 0
.formula M|guvs        = 0
.formula M|guvh        = 0
.formula M|bils        = 0
.formula M|bilh        = 0
.formula M|guvsum      = 0
.formula M|bilsum      = 0
.formula M|ggvkzs      = 0
.formula M|ggvkzh      = 0
.formula M|gvkzsal     = 0
.continue END
..
..*****************************************************************************
!END
..*****************************************************************************
.continue
