..!interpreter english translate noabbrev
..*****************************************************************************
.. FOP-Name       : USTNACH.INIT
.. Autor          : male
.. Verantwortlich : cl
.. Kontrolle      : mh
.. Funktion       : Initialisierung der Ausgabefelder in den IS fb/USTKONACH und fb/USTBUNACH
.. Functionality  :
..*****************************************************************************
..
..
..*****************************************************************************
..
.set trans -
..
.make screen line --
.continue END
..
..*****************************************************************************
!END
..*****************************************************************************
.continue
