..!interpreter english translate noabbrev
..*****************************************************************************
.. FOP-Name       : USTPOSNACH.INIT
.. Autor          : male
.. Verantwortlich : cl
.. Kontrolle      : mh
.. Funktion       : Initialisierung der Ausgabefelder in den IS fb/USTPOSKONACH und fb/USTPOSBUNACH
.. Functionality  :
..*****************************************************************************
..
..
..*****************************************************************************
..
.set trans -
..
.make screen line --
.formula M|ssum  = 0
.formula M|hsum  = 0
.formula M|saldo = 0
.continue END
..
..*****************************************************************************
!END
..*****************************************************************************
.continue
