..!interpreter english translate noabbrev
..*****************************************************************************
.. FOP-Name       : VKZ.INIT
.. Autor          : male
.. Verantwortlich : cl
.. Kontrolle      : mh
.. Functionality  : Initialize screen values
..*****************************************************************************
..
.set trans -
..
.make screen line --
.type integer xperiod ? _F|defined(U|xperiod)
.formula U|xperiod = 1
..*****************************************************************************
!LOOP
..*****************************************************************************
.continue END ? U|xperiod > M|maxperiod
.formula M|asollsum.U|xperiod    = 0
.formula M|ahabensum.U|xperiod   = 0
.formula M|vkzsollsum.U|xperiod  = 0
.formula M|vkzhabensum.U|xperiod = 0
.formula M|esollsum.U|xperiod    = 0
.formula M|ehabensum.U|xperiod   = 0
.formula M|ganfsal.U|xperiod     = 0
.formula M|vkzsal.U|xperiod      = 0
.formula M|gessum.U|xperiod      = 0
.formula M|ggvkzs.U|xperiod      = 0
.formula M|ggvkzh.U|xperiod      = 0
.formula M|gvkzsal.U|xperiod     = 0
.formula M|gesumsatz.U|xperiod   = 0
.formula M|gesbuumsatz.U|xperiod = 0
.formula U|xperiod = U|xperiod + 1
.continue LOOP
..
..*****************************************************************************
!END
..*****************************************************************************
.continue
